function getDailyQuestions(val) {
  var startDate = new Date("01/17/2023");
  var endDate = new Date(val);
  iteration = ((endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)) + 1;
  
  if (val == "01/17/2023") {
    daily0 = ["Metals",["The Statue of Liberty is sheathed in more than 31 tons of this metal mined in Norway", "Discovered in Colorado in the 1950s, coffinite is an ore that is more than 60% this radioactive metal","An oxide of this light metal, discovered in 1791, is used extensively as a white pigment","This metal used to make semiconductors was discovered by Clemens Winkler & named for his homeland"],["Copper","Uranium","Titanium","Germanium"]];
    daily1 = ["The Revolutionary War",["The British passed the Intolerable Acts to punish Massachusetts for this event","General Richard Montgomery was killed December 31, 1775 leading a hopeless attack on this Canadian city","Born in Connecticut, Nathan Hale was a graduate of this Ivy League university","In the 1760s painter Charles Willson Peale joined this patriot group, angering Loyalist creditors"],["Boston Tea Party","Quebec","Yale","Sons of Liberty"]];
    daily2 = ["Lakes & Rivers",["Famous for its monster, it forms part of the Caledonian Canal","At 2,485 miles, the Parana is this continent's second-longest river","This largest lake in Africa is also the main reservoir of the Nile River","The pre-Incan Uros people still inhabit floating islands high in the Andes in this lake"],["Loch Ness","South America","Lake Victoria","Lake Titicaca"]];
  } else if (val == "01/18/2023") {
    daily0 = ["Car Talk",["When fixing cars, \"R & R\" means remove & do this to an auto part","This converter reduces the level of harmful pollutants in a car's exhaust","Manual shifters used to come in \"4 on the floor\" & \"3 on\" this arboreal word for the steering column","Inspect the master cylinder, part of the hydraulics sending fluid through the lines for this drum or disc system"],["restore (or replace or repair)","a catalytic converter","tree","the brakes"]];
    daily1 = ["Biology",["Stomata, leaf pores that take in this gas, enlarge when its level in the air drops below normal","This 3-letter suffix denotes a carbohydrate, especially a sugar","There are 3 main types of these in the body--smooth, striated & cardiac","This part of the small intestine is named for the fact that it's about as long as the width of 12 fingers"],["carbon dioxide","-ose","muscles","duodenum"]];
    daily2 = ["5-Letter Words",["To surpass, or a Microsoft spreadsheet program","Honey is an animal product & can be excluded from a strict this type of diet","A musical composition with a repeated theme using multiple voices, or a disturbed state of altered consciousness","The Carabao is a popular variety of this tropical fruit"],["excel","vegan","fugue","mango"]];
  } else if (val == "01/19/2023") {
    daily0 = ["Communication",["56' wide & 29' high, a digital billboard called the Broadway Spectacular is in the heart of this New York City area","With a brain larger than man's, their language is a system of beeps, whistles, & clicks","The 2-way field radio developed by Don Hings for bush pilots in 1937 soon got this snappier name","France's Robert Coulondre, who had this job, presented a futile demarche, a diplomatic note, in Berlin Sept. 1, 1939"],["Times Square","dolphins","walkie-talkies","ambassador to Germany"]];
    daily1 = ["Mississippi",["On Jan. 9, 1861, Mississippi became the 2nd state to do this","In 1898 in Biloxi, Edward Barq began bottling & selling this beverage","He modeled his fictional Yoknapatawpha County on the area around his hometown of Oxford","Over 55% of the land in Mississippi is covered by these"],["secede from the Union","root beer","(William) Faulkner","forests"]];
    daily2 = ["Vocabulary",["If you're piscivorous, you eat this, which can \"net\" you some health benefits","Latin gets its name from \"Latium\", a region of this country","Sometimes it's a pickled flower bud used as a garnish, & sometimes it's a prank or theft","From the Latin for \"earth\", it's another word for patio"],["fish","Italy","a caper","terrace"]];
  } else if (val == "01/20/2023") {
    daily0 = ["Weather",["On a weather map, 3 horizontal & parallel lines indicate this weather condition","From the Middle English for \"fall of dew\", it's a light rain in which the water droplets are less than .5 mm in diameter","Non-fluid aneroid barometers use a partial one of these instead of mercury to measure air pressure","The highest known barometer reading in the U.S., 31.85, was recorded in this state during a 1989 cold wave"],["fog","drizzle","vacuum","Alaska"]];
    daily1 = ["American History",["He died in 1804 the day after his duel with Aaron Burr","Without the knowledge of Congress, James Madison took possession of West Florida from this country","In the 1850s this state was \"Bleeding\" as pro- & anti-slavery forces met up in a preview of the Civil War","The \"separate but equal\" doctrine in the case of Plessy v. this judge upheld racial segregation for almost 60 years"],["Alexander Hamilton","Spain","Kansas","Ferguson"]];
    daily2 = ["Old Testament",["\"And the Lord spake unto the fish and it vomited out\" him \"upon the dry land\"","In the 1st month of their 2nd year in the desert, Moses & the people celebrated this holiday","Leviticus 13 is a symptom guide for this skin disease you hear a lot about in the Bible","Isaiah & Jeremiah are considered major ones, Obadiah & Zechariah, minor"],["Jonah","Passover","leprosy","prophets"]];
  } else if (val == "01/21/2023") {
    daily0 = ["Spiders",["Each of a spider's these contains 7 segments, so that's 56 segments per spider","The spider family Uloboridae lacks these glands, so if you want a pet spider, maybe get one of them","Many garden spiders are among those classed as these \"weavers\" of round webs","1 of the world's most dangerous spiders is this country's Sydney funnel web"],["legs","venom","orb weavers","Australia"]];
    daily1 = ["Europe",["This country that has many satellites built a monument to its 1st satellite","Rossini never visited this Spanish city where he set an 1816 opera","This is the largest & southernmost of the Baltic republics","Bonny Ben Nevis, highest peak in the United Kingdom is in this country"],["Russia","Seville","Lithuania","Scotland"]];
    daily2 = ["Golf",["Bird word for 2 under par on a hole","The \"pitching\" this type of club is used for short, lofted shots","The closely mowed ring of grass around a putting green is called an apron or this out-there name","Exhibiting Bernoulli's Principle, these indentations on a golf ball cause it to lift & stabilize it in flight"],["an eagle","wedge","the fringe","a dimple"]];
  } else if (val == "01/22/2023") {
    daily0 = ["Rock 'N Roll",["In \"American Pie\", Don McLean drove this to the levee","The concert theatrics of this band included Pete Townshend smashing his guitar to bits","Peter & Gordon's hit, \"World Without Love\", was written by this Beatle pair","In 1985, Tears for Fears said \"everybody wants to\" do this"],["Chevy","The Who","Lennon & McCartney","rule the world"]];
    daily1 = ["Pop Music",["Ariana Grande sings, \"When all is said & done, you will believe\" this, a 2018 song that mixes spirituality & female power","A song by Zedd, Maren Morris & Grey asks, \"Oh baby, why don't you just meet me in\" this title place","In 2015 Zayn Malik officially quit this band","\"Somebody Told Me\" that The Killers were formed in this city in 2002"],["\"God Is A Woman\"","the middle","One Direction","Las Vegas"]];
    daily2 = ["Opera",["This opera ends with the title madam committing hara-kiri","Don Jose is bewitched by this title gypsy girl","Mozart opera in which the count tries to thwart & postpone his valet's wedding","Peter Cornelius' opera \"The Barber of Baghdad\" was based on a tale in this collection"],["Madame Butterfly","Carmen","The Marriage of Figaro","Arabian Nights"]];
  } else if (val == "01/23/2023") {
    daily0 = ["Cats",["An old name for Thailand is in the name of this breed that sometimes has crossed eyes","Shorthaired cats were derived from the caffre cat, which was domesticated by this ancient civilization","In the 1960s officials of the Ankara, Turkey zoo saved this pure breed from extinction","Kittens have 26 of these, adult cats 30"],["a Siamese","Egypt","the Turkish Angora","teeth"]];
    daily1 = ["Food Facts",["This word was once used for the meat of any hunted animal; now it refers to deer meat","A genoise is a light sponge cake whose name is derived from this city","Mostly made from the whites, egg substitutes don't contain fat or this artery-clogging lipid","Cannellini is a white kidney bean, cannelloni is a type of this"],["venison","Genoa","cholesterol","pasta"]];
    daily2 = ["Medicine",["The A1C test measures average blood sugar over the past 3 months; at 5.7% you're pre-this, at 6.5 you're this","In this \"effect\" people are given inert substances & seem to improve","Named for an American surgeon, McBurney's incision is a cut in the lower right abdomen used when removing this","Often found in areas with large deer populations, this bacterial inflammatory disease was first identified in 1975"],["diabetic","placebo","the appendix","Lyme disease"]];
  } else if (val == "01/24/2023") {
    daily0 = ["Flags",["Fiji's flag depicts many of its tropical treasures, including sugar cane, bananas & this type of palm","The diamond shape on its flag references the fact that it was the only diamond-producing U.S. state","The fortress on the flag of this British overseas territory symbolizes its strategic importance on the Mediterranean","The blue & white in Somalia's flag were influenced by the flag of this body that has played a role in Somali history"],["a coconut tree","Arkansas","Gibraltar","the United Nations"]];
    daily1 = ["Children's Literature",["Sketches written for Punch became his first novel, \"Lovers in London\"; Winnie-the-Pooh came 21 years later","\"One Sunday morning the warm sun came up and--pop!--out of the egg came\" this title larva","A young rabbit gets ready for bed in this classic by Margaret Wise Brown","Thing One & Thing Two are characters in this 1957 Seuss classic"],["(A.A.) Milne","the Very Hungry Caterpillar","Goodnight Moon","The Cat in the Hat"]];
    daily2 = ["Animal Adjectives",["Vulpine, like the bat-eared or the crab-eating","Ostracean, like the Olympia or the pearl","Anserine, like the snow or the nene","Columbine, like the rock or the mourning"],["the fox","an oyster","a goose","a dove"]];
  } else if (val == "01/25/2023") {
    daily0 = ["Mathematics",["The exact value of this, the ratio of a circle's circumference to its diameter, can't be written down","This type of \"strip\", a continuous flat loop with 1 twist, has only 1 surface","In Roman numerals, the largest number represented by a single letter with no markings","A set with no elements is described as this"],["pi","a Möbius strip","1,000 (the letter M)","Null / empty"]];
    daily1 = ["Science",["Every second, fusion reactions in the Sun convert about 600 million tons of this element into helium","Newly created nihonium is classified as a \"trans-\" this element","During a total solar eclipse, you can glimpse this \"colorful\" layer of the Sun just above the photosphere","First predicted in 1930, this particle with no charge goes through miles of matter without reacting with a proton or neutron"],["hydrogen","transuranium","the chromosphere","neutrinos"]];
    daily2 = ["History",["An international force seized Beijing on August 14, 1900, crushing this rebellion","Name of the king who after beating Rome at Asculum but taking heavy casualties, said one more such win would undo him","In 1950 & then again in 1951, this capital city fell to invading forces who were evicted each time by U.N. troops","The USA's worst depression before the Civil War began with what's usually called this event \"of 1837\""],["the Boxer Rebellion","Pyrrhus","Seoul","the Panic"]];
  } else if (val == "01/26/2023") {
    daily0 = ["Geography",["Lahore, this country's second-largest city, is the capital of the Punjab province","This Italian region that includes Pisa & Florence gets its name from the Etruscan people","If you're on Nevis & have business at Government House, you need to go to this nearby island","Afrikaner Gert Alberts was the leader of a famous crossing of this desert in the 1870s"],["Pakistan","Tuscany","St. Kitts","the Kalahari Desert"]];
    daily1 = ["Languages",["Standard Chinese is based primarily on this form of Chinese spoken by the educated in Beijing","This language is spoken by about 11 million in Europe & about 200 million in South America","L.L. Zamenhof grew up in an area of Poland where 4 languages were spoken, leading to ethnic animosity, so he created this","The language of this small Balkan country has 2 main dialects: Gheg & Tosk"],["Mandarin","Portugese","Esperanto","Albania"]];
    daily2 = ["Constellations",["The brightest star in Bootes is this color giant & is 100 times more luminous than the sun","With this constellation winding around it, Ursa Minor must hope it isn't fire-breathing","The Pup is the companion to this star in Canis Major","This constellation's second-brightest star, Shaula, is also known as \"the Stinger\""],["red","Draco","Sirius (the Dog Star)","Scorpio"]];
  } else if (val == "01/27/2023") {
    daily0 = ["Dragons",["In this novel, Bilbo Baggins, Gandalf & 13 dwarves reclaim Lonely Mountain & its riches from the dragon Smaug","In Babylonian myth, the dragon Tiamat's upper half becomes Heaven; the lower half, this","This Scandinavian prince rid the Danes of the monster Grendel; 50 years later he was killed by a dragon","Last name of King Arthur's father Uther, derives from the Welsh, meaning \"head\" or \"chief\""],["The Hobbit","the earth","Beowulf","Pendragon"]];
    daily1 = ["Farming",["Driving 20-ton vehicles on farmland can mean that the next year you'll get \"stuck in\" one of these, defined as a wheel track 3\" deep","In July 2019 dozens of farmers of these beans went to congress, demanding a deal be made to resume trading with China","Heinz sauces--er, sources--ketchup tomatoes from this state's vast & fertile Central Valley","Applied to farmland, it means left without sowing for a period in order to restore its fertility"],["a rut","soybeans","California","fallow"]];
    daily2 = ["Guinness Records",["Takabisha, the steepest one of these, has a free-falling angle of 121 degrees; your move, Space Mountain","Talk about a special day! Romanian model Ema Dumitrescu's wedding dress had a 1.85-mile-long one of these","A 1759 document records Arthur Guinness signing a 9,000-year lease on a brewery at St. James' Gate in this city","In 2004, Tia, a mastiff, gave birth to the largest litter of these ever--24"],["a rollercoaster","a train","Dublin","puppies"]];
  } else if (val == "01/28/2023") {
    daily0 = ["Words",["This name for a work of art that you may carve in art class comes from the Latin for \"to carve\"","The name of these small towers often seen on castles comes from Old French for \"small towers\"","This word for a white wine & soda drink first appeared in Webster's in 1961","A harsh expression substituted for a more neutral one is a dysphemism & this is the opposite"],["sculpture","turrets","spritzer","euphemism"]];
    daily1 = ["Chemistry",["The lipids, which include fats & oils, are organic compounds that don't appreciably interact with this","Relative atomic mass is another name for this","Acids & bases are among these current conductors; using a solid instead of a liquid one reduces the risk of fire in batteries","This brown pigment of hair, skin & eyes is a polymer"],["water","atomic weight","electrolytes","melanin"]];
    daily2 = ["Games",["Each player is dealt 26 cards in this game; if both players turn up a card of the same rank, it's this, the name of the game","In the game of Hearts, this card is known as \"The Black Lady\"","Join in & tell us that this is the lowest-rated suit in contract bridge","In U.S. croquet, a ball that goes through all the wickets has this travelling name, especially if it's the red one"],["War","the queen of spades","clubs","a rover"]];
  } else if (val == "01/29/2023") {
    daily0 = ["Fitness",["Sprinting & powerlifting are examples of this type of exercise that means \"without oxygen\"","Referring to exercise that raises your heart rate and gets your blood flowing, \"cardio\" is short for this","To improve balance, try this ancient exercise with a Chinese name that means \"supreme ultimate fist\"","It's the \"electrical\" term for the amount of weight or pressure involved in an exercise"],["anaerobic","cardiovascular","tai chi","resistance"]];
    daily1 = ["Ancient Rome",["The last emperor of Rome, who was overthrown in 476, shared his name with this legendary founder of the city","Carved on stone or metal, the acta diurna was an early newspaper posted this often in a public area","Roman roads were built with concrete made from pozzolana, ash from these; the roads by Pompeii must've been good","Latin for \"father of the family\", he was the oldest living male of the family & had total control of his household"],["Romulus","daily","volcanoes","pater familias"]];
    daily2 = ["Plants",["In 2006 the city of L.A. Iimited its planting of this tall tree because it's disease-prone, non-native & gives little shade","Archaeologists have found that varieties of this grain, like Emmer & Einkorn, were grown in the 7th millennium B.C.","Fungi not only lack roots, stems & leaves, but also this food-making matter","This tree's name comes from the Hindi word for \"trader\" because people displayed their wares in its shade"],["the palm","wheat","chlorophyll","the banyan tree"]];
  } else if (val == "01/30/2023") {
    daily0 = ["Fictional Characters",["She is the narrator of \"To Kill a Mockingbird\"","This character in \"The Legend of Sleepy Hollow\" is said to be the ghost of a Hessian trooper","As this book begins, Santiago had \"gone eighty-four days... without taking a fish\"","For stealing a loaf of bread during the French Revolution, he ended up serving 19 years"],["Scout (Jean Louise Finch)","the Headless Horseman","The Old Man and the Sea","Jean Valjean"]];
    daily1 = ["Starts With \"A\"",["The Rhode Island Greening is a tart one of these you can use to make tarts","Dappled horse believed to have descended from wild mustangs in Nez Perce territory","Richard the Lion-Heart was duke of this French area that his mother Eleanor had inherited","From the Latin word for \"tree\", it's a place where many kinds of trees & plants are exhibited"],["an apple","an appaloosa","Aquitaine","arboretum"]];
    daily2 = ["Alphabet Soup",["T is for this soup that's paired with grilled cheese on the Campbell's Kitchen website","B is for this thick 6-letter soup, perhaps lobster or mushroom","A is for this spicy Mexican soup whose name is Spanish for \"meatball\"","\"F\" is for this soup with a little cheesy goodness on top"],["tomato","bisque","albondigas","French onion soup"]];
  } else if (val == "01/31/2023") {
    daily0 = ["20th Century America",["Its 1980 eruption was the first by a volcano in the continental U.S. outside Alaska since 1917","In 1954 Senator Joe McCarthy provoked televised hearings after accusing the army of \"coddling\" these people","This first Disney animated feature had its world premiere on December 21, 1937","Tragically, on January 28, 1986 this exploded 73 seconds after liftoff"],["Mount St. Helens","communists","Snow White and the Seven Dwarfs","the Challenger"]];
    daily1 = ["Birds",["Perhaps this \"thrush\", a type of babbler, hangs out at comedy clubs with the same-named hyena","During mating season the male ruff develops a large frill of feathers around this body part","From the elaborate dwellings wrens build, their Latin family name is this, meaning \"cave-dweller\"","The gray jay is not as famous as this relative whose scientific name is Cyanocitta cristata"],["laughing thrush","neck","Troglodytes","the blue jay"]];
    daily2 = ["Italian Art",["Lesser known works by this Italian master include \"The Virgin Of The Rocks\" & \"The Adoration Of The Magi\"","Dazzling works by Bernardo Strozzi of Genoa include one of this woman's \"Annunciation\"","One of the greatest painters of the Venetian school, this 16th century artist was born Tiziano Vecellio","Circa 1415, Donatello carved a marble relief of this man slaying a dragon"],["Leonardo da Vinci","Mary","Titian","St. George"]];
  } else if (val == "02/01/2023") {
    dailyArr = [ ["Water",["Hydrolysis uses water to destroy these that hold a compound together","Water has low this \"V\" property, meaning it's quick to flow or change shape","Usually using zeolite or an ion-exchange resin, this process removes minerals from water","Known to the ancients, these wells are named for a French province where they were 1st drilled c. 1100"],["bonds","viscosity","water softening","artesian"]], ["Early Man",["790,000-year-old flints from a site in Israel provide the oldest known evidence of early man's control of this","Around 11,000 B.C. people in Greece sailed over 70 miles to Melos to get this volcanic glass for tools","The enlarged brain of this early human species helped it become the longest-lived member of the human family tree; named for its upright posture, it survived nine times longer than our species has been around","The Chalcolithic Age is named for this, the 1st metal discovered by man"],["fire","obsidian","homo erectus","copper"]], ["Literary Quotes",["He \"Appeared on the sidewalk with a bucket of whitewash and a long-handled brush\"","This title character: \"On the first of September 1651, I went on board a ship bound for London\"","In this Poe story, \"I had scarcely stepped from my... bed of horror... when the motion of the hellish machine ceased\"","In a Hans Christian Andersen story, an old woman tells her that her beautiful tail is \"thought on Earth to be quite ugly\""],["Tom Sawyer","Robinson Crusoe","The Pit and the Pendulum","the Little Mermaid"]]];
  } else if (val == "02/02/2023") {
    dailyArr = [ ["Hobbies",["A life list (which might include auks) & binoculars are used in this hobby","Collecting coins can be lucrative if you have one from 44 B.C. minted by Marcus Mettius showing this Roman","At the Merseyside Maritime Museum, Des Newton would delight kids by showing how to make these impossible-seeming models","Settle in with some needlework & crochet this cozy blanket that gets its name from the land of the Pashtun people"],["birdwatching","Julius Caesar","ships in a bottle","afghan"]] , ["In the Dictionary",["A Biblical woman's name, it means pity but is usually found before \"-less\" to mean pitiless","This word for the animals of a particular region is from the Latin","It's defined as any substance with the tendency to produce a cancer","It's the long word specifically for a 150th anniversary"],["ruth","fauna","a carcinogen","a sesquicentennial"]] , ["Social Studies",["Bernie Sanders spent much of 2016 urging change to this 2-word Latin term for the existing state of affairs","This group is composed of those of your same age or social position; in a courtroom, you might face a jury of them","A 1951 work on this person in societies of northern Asia says he is \"magician and medicine man... priest, mystic and poet\"","This social science focuses on the characteristics of human populations such as size, growth & distribution"],["the status quo","peers","a shaman","demography"]] ];
  } else if (val == "02/03/2023") {
    dailyArr =  [ ["Ranks & Titles",["Going down the ranks of the Royal Navy, remember your 3 C's: commodore, captain, this","As one of these enlisted ranks in the army, your grade is E-1 or E-2; as a first class one, it's E-3","Latin for \"to earn by service\", this honorary title often follows the name of a retired college professor","Title for the sovereign prince of Austria's royal family; Francis Ferdinand was one"],["commander","private","emeritus","Archduke"]], ["Cooking",["Butterball advises putting the thermometer in this part of the turkey that provides dark meat","Hungarian goulash recipes measure salt & pepper in teaspoons or tablespoons, but this spice in cups","Also sometimes done to harbors, it means to coat food with a dry ingredient like flour","Ricotta isn't a cheese, it's a cheese by-product made from this liquid drained from cheeses"],["the thigh","paprika","dredge","whey"]] , ["Number Please",["Number of toes on each front paw of most cats","Decennoval refers to this number that's also the atomic number of potassium","In baseball, the sum of balls & strikes represented by a full count","The word myriad can refer to any large number of things, or specifically to this big number"],["5","19","5","10,000"]] ];
  } else if (val == "02/04/2023") {
    dailyArr = [ ["kid stuff", ["They were first allowed to play Little League ball in 1974", "When kids play it in England, they jump on 2 legs instead of 1 & hold the \"puck\" between their feet", "\"The Incredible Journey\" described the incredible journey of 2 dogs & 1 of these", "\"Moonwalker\" is the video game in which this rock legend outdances bad guys"], ["girls", "hopscotch", "Siamese cat", "Michael Jackson"]], ["trees", ["Gifted from Japan as a token of friendship in 1912, here are these trees doing their thing in Washington, D.C. as only they can", "To identify the family to which the California nutmeg is related, you might sing \"It had to be...\" this", "The aromatic oil from this Australian gum tree is used in expectorants & inhalers", "(Jimmy of the Clue Crew shows a botanical photo on the monitor.) Broad rings on a tree indicate years of sunshine & rain; narrow rings indicate cold or this weather condition, from the Middle English for \"dryness\""], ["a cherry blossom", "yew", "the eucalyptus", "drought"]], ["asia", ["Some believe our numerals, which we know as \"Arabic\", came from this subcontinent in the 8th century", "Sometimes this country is referred to as East Bengal", "Part of the Old Palace of the Malla kings, the Taleju Temple is found in this capital of Nepal", "Because of the high cost of living in this Asian capital, Uganda had to close its embassy there"], ["India", "Bangladesh", "Kathmandu", "Tokyo"]] ];
  } else if (val == "02/05/2023") {
    dailyArr = [ ["u.s. beaches", ["So. California city that's home to the Queen Mary, the Spruce Goose & a lengthy swath of surf", "Neil Simon has fond \"Memoirs\" of it", "\"Where the boys\" were in '60 & again in '84", "Largest city in Virginia, this beach is also state's #1 resort"], ["Long Beach", "Brighton (Beach)", "Ft. Lauderdale", "Virginia Beach"]], ["all numbers", ["Number of seconds in 1Â½ minutes", "The highest number on a roulette wheel", "It's .083 feet", "A teen's \"sweet\" age"], ["90", "36", "an inch", "16"]], ["starts with \"oo\"", ["Said when you make a faux pas", "Loads, gobs, or heaps of anything", "Name for beer hall brass band that plays like this:", "Chinese tea for two"], ["oops", "oodles", "oompah", "oolong"]] ];
  } else if (val == "02/06/2023") {
    dailyArr = [ ["sports trivia", ["Winner of more major golf tournaments than anyone else, he's known as \"Slammin' Sam\"", "1st royal member of Int'l Tennis Hall of Fame, King Gustav V brought the game to this country", "Rogers Hornsby favored baseball over this sport, saying, \"When I hit a ball I want somebody else to go chase it\"", "Near the end of a round in this Apr. '88 NFL event, some people began humming the Jeopardy! \"Think\" music"], ["Snead", "Sweden", "golf", "NFL Draft"]], ["insects", ["The female cockroach has a packing case for these & carries it until she finds a good spot for them", "A long-horned grasshopper gets this name from the love call produced by rubbing its two front wings together", "Of the 3 classes of honeybees, the 1 whose name could describe the sound of a hive", "\"Circuses\" of these insects have been trained to do tricks such as pulling tiny wagons"], ["her eggs", "the katydid", "drone", "flags"]], ["cooking", ["Butterball advises putting the thermometer in this part of the turkey that provides dark meat", "These, also known as grissini, can be sprinkled with sesame seeds before baking", "Gamblers might like this oyster dish made with green onions or shallots & bacon", "To make hard sauce, start by beating sugar & this bread spread together until smooth & creamy"], ["the thigh", "breadsticks", "oysters casino", "margarine (butter)"]] ];
  } else if (val == "02/07/2023") {
    dailyArr = [ ["\"ben\"", ["Goodman, Hill, or Jack", "An Indian tiger", "Each year this cigarette company's contest offers 100 unusual prizes", "You bet your life this person will profit from your insurance policy"], ["Benny", "a Bengal tiger", "Benson & Hedges", "your beneficiary"]], ["gardens", ["Not flowers but hotels & houses grow on this Monopoly board \"garden\"", "In the 1800s city founders designed Macon, Georgia to look like this ancient city known for its gardens", "This site has seen more than its share of historic & ceremonial occasions", "For the gardens of this palace just outside Paris, Louis XIV had trees brought from all the French provinces"], ["Marvin Gardens", "Babylon", "the Rose Garden", "Versailles"]], ["first ladies", ["When she married the future president in 1759, she was said to be the richest marriageable woman in Virginia", "1950s first lady who was so fond of pink that in her day the White House was called \"the Pink Palace\"", "This first first lady was an accomplished knitter", "First Lady for most of the 1950s, she was a big fan of \"As The World Turns\""], ["Martha Washington", "Mamie Eisenhower", "Martha Washington", "Mamie Eisenhower"]] ];
  } else if (val == "02/08/2023") {
    dailyArr = [ ["butlers", ["6'9\" TV butler, he always entered the room with a deep \"You rang?\"", "William Powell & David Niven both played this bum-to-butler role", "He received '81 Oscar for playing \"Arthur's\" butler", "The valet given to Bertie Wooster by P.G. Wodehouse"], ["Lurch", "My Man Godfrey", "John Gielgud", "Jeeves"]], ["weapons", ["Movie name given to the theory of weapons in space debated by Reagan & Mondale", "An AA gun is a weapon designed as anti- this", "In the Marine Corps the next rank up from PFC has this weapon in its name", "This spear's name is from the Latin for \"three-toothed\""], ["Star Wars", "aircraft", "lance", "a trident"]], ["virginia", ["Slavery was introduced into what would become the U.S. in this Virginia settlement in 1619", "You go there to visit the Tomb of the Unknown Soldier", "This capital was among the 1st U.S. cities to have an electric streetcar system", "When little George Washington moved here as a tot, it was called Little Hunting Creek Plantation"], ["Jamestown", "Arlington National Cemetery", "Richmond", "Mount Vernon"]] ];
  } else if (val == "02/09/2023") {
    dailyArr = [ ["easy math", ["The answer to 65 divided by 4/7 x 0", "The number of senators divided by the number of states", "An isosceles triangle has this many sides equal in length", "On a flat surface, it's the shortest distance between two points"], ["zero", "2", "2", "straight line"]], ["pop quiz", ["According to the Beatles hit, it's when \"love was such an easy game to play\"", "An early label for this soda showed a hillbilly shooting at a revenuer running from an outhouse", "He fathered baseball * Barry Bonds", "\"Because the Night\" was a big hit from this Natalie Merchant group's \"MTV Unplugged\" album"], ["Yesterday", "Mountain Dew", "Bobby Bonds", "10,000 Maniacs"]], ["food facts", ["Jimmy Dean's new flapsticks are sausages dipped in this batter & stuck on sticks", "In Chinese cuisine, pancakes kept in a steamer are often called these, like small ornamental mats", "This hard-shelled high calorie nut, native to Australia, is also called the Queensland nut", "You should hard-boil these breakfast items before adding them to your chiffonade dressing"], ["pancake batter", "doilies", "macadamia", "eggs"]] ];
  } else if (val == "02/10/2023") {
    dailyArr = [ ["crime & punishment", ["In California, this auto necessity is made at Folsom Prison", "By age 33, John MacLean, this type of thief, had stolen $150 mil. worth of goods by himself", "The Library Awareness program is an effort by this bureau to flush out Soviet spies", "\"Fishy\" name for the usurious crime of lending money at extremely high rates of interest"], ["license plates", "a burglar", "the FBI (Federal Bureau of Investigation)", "loan sharking"]], ["egypt", ["Egyptian-born actor Michael Shalhoub, his most famous role was a Russian doctor", "While the pharaohs built ancient wonders, Ferdinand de Lesseps built this \"modern\" one", "Though this dam controls the Nile's flood waters, some say it's harmed the environment", "This glamour girl reigned in Egypt from 51 to 31 B.C."], ["Omar Sharif", "the Suez Canal", "Aswan High Dam", "Cleopatra"]], ["quote, unquote", ["Play in which Queen Gertrude, while watching a play, says, \"The lady doth protest too much\"", "At the 1st Battle of Bull Run, Bernard Bee said, \"There is Jackson, standing like...\" this", "Pop artist who claimed \"in the future everyone will be famous for 15 minutes\"", "\"I can't mate in captivity.\" explained this feminist on why she's never married"], ["Hamlet", "a stone wall", "Andy Warhol", "Gloria Steinem"]] ];
  } else if (val == "02/11/2023") {
    dailyArr = [ ["famous pigs", ["Kermit's hot hog", "A famous phrase of theirs was \"Not by the hair of our chinny chin chin\"", "Scientists believe that the babirusa pig might qualify for this Jewish clean food status", "The Ziffels of Hooterville's son"], ["Miss Piggy", "the Three Little Pigs", "kosher", "Arnold Ziffel"]], ["trivia", ["In 1796, this Frenchman confessed, \"When I see an empty throne I feel the urge to sit on it\"", "N.M.I. means this, as used in the name John (N.M.I.) Smith", "Filing an IRS form 4868 gets you a 4-month extension from this date", "He said, \"I came in with Halley's comet in 1835 & I expect to go out with it\""], ["Napoleon", "no middle initial", "April 15", "Mark Twain"]], ["u.s. cities", ["It's the \"City of Big Shoulders\" as well as the \"Windy City\"", "This city whose name means \"yellow\" is the largest city in the Texas panhandle", "Titusville is considered the gateway to this Florida space center at Cape Canaveral", "After the Twin Cities & Bloomington, Duluth is this state's next most populous city"], ["Chicago", "Amarillo", "the Kennedy Space Center", "Minnesota"]] ];
  } else if (val == "02/12/2023") {
    dailyArr = [ ["the '50s", ["Company which popularized the Hula Hoop in America", "The first non-stop transcontinental flight in this type of craft took 32 hours in 1956", "When Hurricane Carol hit New England it toppled the steeple from this historic church", "Like, to these cats & chicks, Kerouac was the most"], ["Wham-O", "a helicopter", "the Old North Church", "the beatniks (the Beat Generation)"]], ["double meanings", ["Dashing to the florist, or the Kentucky Derby", "A den painted deep red, or Sherlock Holmes' first story", "Now that he no longer has ___ from his wound, we can ___ the patient from the hospital", "Swift, or the largest organized unit of naval ships"], ["the Run for the Roses", "A Study in Scarlet", "discharge", "fleet"]], ["sports", ["At the 1924 Olympics he broke the 1-minute barrier in the 100-meter freestyle & he wasn't swinging on vines", "This breed of horse got its name from its ability to run a 1320' race quickly", "Prior to par, this term was used for the score golfers should make, and was preceded by Colonel", "The Greco-Roman form of this sport is very popular in Scandinavia"], ["Johnny Weissmuller", "quarter horse", "bogey", "wrestling"]] ];
  } else if (val == "02/13/2023") {
    dailyArr = [ ["rituals", ["You remove them before entering a house in Japan", "Part of a pilgrim a Pope washes on Maundy Thursday", "While Laplanders hae an involved ritual for this, Eskimos just touch noses", "Someone saying \"God bless\" after you do this is said to keep your soul from wandering"], ["your shoes", "feet", "kissing", "sneezing"]], ["mammals", ["In Tibet a cross between domestic cattle & this wild ox is called a dzo", "Because of man, the zebra-like quagga & Steller's sea cow are both this", "The primate order is characterized by having these instead of claws", "These range in size from the 3-foot-long sun to the over 9-foot long Alaska brown"], ["a yak", "extinct", "fingernails", "bears"]], ["television", ["The 2017 edition of this reality competition had designers working with models from size 2 to size 22", "\"Dynasty\" character who's been married to Blake Carrington, Cecil Colby & \"Dex\" Dexter", "\"It's Howdy Doody time, it's Howdy Doody time, Bob Smith and Howdy too say\" this \"to you\"", "This Sunday night series is subtitled \"The New Adventures of Superman\""], ["Project Runway", "Alexis", "howdy do", "Lois & Clark"]] ];
  } else if (val == "02/14/2023") {
    dailyArr = [ ["flowers",["This special flower for March lies at one end of the spectrum, so to speak","This flower's name comes from the Greek word for rainbow, not from part of your eye","This large group of flowering plants attracts serious devotees, like those who pay $10,000 for one Peruvian plant","This climbing vine's funnel-shaped flowers open shortly after dawn for just a few hours"],["violet","iris","orchids","morning glory"]], ["chocolate",["Named for a port in Yemen, mocha is what Americans call the combination of chocolate & this","Emeril's recipe for chocolate-covered turtles doesn't actually call for turtles but for these nuts","White chocolate is actually not chocolate--it is milk & sugar mixed with this, the edible fat of the cocoa bean","This company's classic bag of miniatures includes Mr. Goodbars & small versions of the milk chocolate bar"],["coffee","pecans","cocoa butter","Hershey's"]] , ["love",["Chaucer, Shakespeare & Blake are among the poets who have written that love has this disability","Some regard this purple quartz gem as a love charm","In an 1850 poem he wrote, \"Tis better to have loved and lost than never to have loved at all\"","This book of the Old Testament is basically a collection of love poems"],["it's blind","amethyst","Alfred Lord Tennyson","Songs of Solomon"]] ];
  } else if (val == "02/15/2023") {
    dailyArr = [ ["foods", ["From Dutch meaning \"cabbage salad\", that's just what it is", "\"Nautical\" legume broth, served daily in the U.S. Senate cafeteria", "The food & drink of the gods which bestowed youth & immortality", "Deli delight, from Yiddish for Ring"], ["cole slaw", "Navy bean soup", "nectar & ambrosia", "a bagel"]], ["zoology", ["On television, it \"roars\" for MTM", "In the tropics, these insects may consume up to 1/3 of annual production of dead grass, leaves & wood", "The name of this deadly snake of tropical North & South America is French for \"lance head\"", "The La Plata dolphin is found in the rivers & eastern coastal waters of this continent"], ["a pussycat", "termites", "fer-de-lance", "South America"]], ["travel & tourism", ["(Sarah of the Clue Crew stands overlooking a waterfall.) I'm in this state, known for spectacular scenery such as waterfalls; Shoshone Falls, near Twin Falls, is 20 feet higher than Niagara", "Country where 1000s of tourists flock each year to a desolate region to look at the following:", "The world's tallest tree, a 365-foot redwood, stands in this state's Humboldt County", "The Charles Darwin Research Station on Santa Cruz is a good start for a tour of these South American islands"], ["Idaho", "Australia", "California", "Galapagos Islands"]] ];
  } else if (val == "02/16/2023") {
    dailyArr = [ ["sudden death", ["Every August 23rd a woman in black leaves flowers on this silent star's resting place", "Curiosity committed felicide when it killed this", "Leonard Warren literally died on stage while performing at this New York opera house", "It's who, on June 3 1953, jumped off the Tallahatchee Bridge"], ["Valentino", "the cat", "The Metropolitan Opera House", "Billie Joe McAllister"]], ["u.s. geography", ["The borders of 5 Utah counties lie within this lake", "Apalachee Bay is the eastern edge of this section of Florida stretching 200 miles west", "Sandusky Bay is an inlet of Lake Erie in this state", "Cadillac Mountain, the highest peak on the Eastern Seaboard, lies in this Maine national park"], ["The Great Salt Lake", "the Panhandle", "Ohio", "Acadia National Park"]], ["people", ["In April 2010 People reported this daughter of Tom Cruise is turning 4 with a style all her own", "You won't find Frank J. Zamboni in the Hockey Hall of Fame, but you will find his machine that does this", "She lamented, \"People only want to remember me for that one shower scene in 'Psycho'\"", "This \"Fast Car\" singer honed her style on the Boston circuit while a student at Tufts University"], ["Suri", "clean the ice between periods", "Janet Leigh", "Tracy Chapman"]] ];
  } else if (val == "02/17/2023") {
    dailyArr = [ ["howdy doody", ["He was both the host & voice of Howdy Doody", "Original number of Howdy's freckles, they equaled the number of U.S. states", "This 4 word question was asked at the top of every show, following the words \"Say kids...\"", "Job held by Mr. Cobb in Doodyville; Mr. Hooper on \"Sesame Street\" did the same thing"], ["Bob Smith", "48", "What time is it?", "grocer (general store keeper)"]], ["word origins", ["The name of this colorless Russian spirit is a diminutive of the Russian word for \"water\", itself a colorless liquid", "Before it was used for a musical work, this 4-letter word meaning \"work\" was used by the Romans to designate construction", "Originally made in Nimes, France, this fabric was called serges de Nimes", "From the French for \"something fried\", types include apple, corn & clam"], ["vodka", "opus", "denim", "a fritter"]], ["weights & measures", ["A metric one of these is equal to around 2,204 pounds", "A nail, an ell & a bolt are all used to measure this", "This unit of area is equal to 4,840 square yards", "In the 14th century Edward II declared it was equal to 3 barley corns laid end-to-end"], ["a ton", "cloth", "an acre", "an inch"]] ];
  } else if (val == "02/18/2023") {
    dailyArr = [ ["odd jobs", ["In the 1950s famous ones were Doreen, Sharon, Bobby, Cheryl, Annette, Karen & Cubby", "They come in air raid, game, or prison varieties", "If you were known as a trailblazer, you did this to trees along the route", "A sailor who created this carved whale ivory was called a scrimshoner"], ["Mouseketeers", "wardens", "mark them with an X (notch them)", "scrimshaw"]], ["politics", ["You're on this \"wing\" if you support traditional values & the conservative party line", "\"Free\" political party formed in 1848 to oppose the extension of slavery", "Military-sounding term for a local leader who oversees a political party's activities in one precinct", "This movement, whose name harkens back to the 1770s, made its first big splash with rallies on Tax Day 2009"], ["right-wing", "the Free Soil Party", "a captain", "the Tea Party"]], ["baseball", ["(Sarah of the Clue Crew reports from the Ronald Reagan Presidential Library.) In San Diego on August 4, 2007, Barry Bonds hit this ball 382 feet to tie the all-time home run record of this man, technically", "In 1944, he led the American League in batting while at the same time managing the Cleveland Indians", "In 1980 this K.C. Royals 3rd baseman hit .390, the highest average since Ted Williams hit .406 in 1941", "This current baseball player is they only man in history to have more than 1,000 career stolen bases"], ["Hank Aaron", "Lou Boudreau", "(George) Brett", "Rickey Henderson"]] ];
  } else if (val == "02/19/2023") {
    dailyArr = [ ["movies", ["A pet parrot named Blu ends up in Brazil to find his mate in this film", "In his last film, he played himself, not Robin Hood, as an ally of Castro's rebels", "The Brothers Gibb were very big in this 1978 musical based on Beatles' music", "Word that completes the titles \"Red...\", \"Dead...\", \"Body...\" & \"Border...\""], ["Rio", "Errol Flynn", "Sgt. Pepper\'s Lonely Hearts Club Band", "heat"]], ["australia", ["1 of 2 animals on its coat of arms", "Reportedly, 2/3 of the 330.000 Australians who served in this 20th C. war wounded or killed", "Land in the center of the continent has been designated as reserves for these people", "After America won its independence, the British decided to ship these people to Australia"], ["(1 of) kangaroo and emu", "World War I", "Aborigines", "convicts (prisoners)"]], ["\"cat\" egory", ["Malcolm McDowell & Nastassja Kinski's \"purr\"fect roles in 1982", "Ancient weapon kept a stone's throw from its target", "Elizabeth Taylor character that could have burnt her paws on a hot tin roof", "It's not a bunch of cats, but a bunch of cows"], ["cat people", "a catapult", "Maggie the Cat", "cattle"]] ];
  } else if (val == "02/20/2023") {
    dailyArr = [ ["gangster movies", ["In gangster gab, they're \"choppers\", \"rods\" & \"gats\"", "Shelley Winters' \"Bloody Mama\"", "\"Asphalt Jungle's\" gorgeous golden-haired gun moll", "Color of the \"Heat\" that Jimmy Cagney felt in classic '49 flick"], ["guns", "Ma Barker", "Marilyn Monroe", "White"]], ["scotland", ["Lively \"Highland\" dance", "Scottish ones consist of 15 people, & their decisions don't have to be unanimous; a majority will do", "This capital's Princes Street Gardens has the world's 1st floral clock, which was built in 1903", "When in Scotland, the queen often stays at the luxurious palace of Holyroodhouse in this city"], ["the Highland fling", "a jury", "Edinburgh", "Edinburgh"]], ["the '30s", ["He was voted Boxer of the Yr. 3 times during the decade", "According to the popular song, \"It don't mean a thing, if it ain't got that...\"", "The Nuremberg Laws of 1935 made the flag bearing this symbol the official one of Germany", "On Nov. 7, 1332 Lucerne joined 3 other forest cantons in this confederation"], ["Joe Louis", "swing", "swastika", "the Swiss Confederation"]] ];
  } else if (val == "02/21/2023") {
    dailyArr = [ ["leaps & jumps", ["Its distinguishing characteristic is February 29th", "Auto part you attach a cable to in order to jump-start a car", "To Annie, these were \"leapin'\"", "In this 440 you go: 13 strides, jump, 13 strides, jump, etc."], ["leap year", "a battery", "lizards", "the hurdles"]], ["grammar", ["This part of speech can be transitive or intransitive", "When reading this clue, a dangling one of these is included", "In the sentence \"It was as if an occult hand had been at work\", \"occult\" is this part of speech", "These are always written out as words when appearing at the beginning of a sentence"], ["verb", "participle", "an adjective", "numbers"]], ["animals", ["Generally batting leadoff alphabetically, this \"earth pig\" has a foot-long tongue", "The only African bird of prey with terrestrial habits; it can't type or take dictation", "The chocolate point, a type of this Asian cat, should have points the color of milk chocolate", "Among the largest flying birds are the California & Andean species of these"], ["an aardvark", "the secretarybird", "a Siamese", "Condor"]] ];
  } else if (val == "02/22/2023") {
    dailyArr = [ ["shaping up", ["What runners call the popular 6.2 mile road race", "Her \"Workout\" is an all-time Top-5 video cassette", "Body-builders' nickname for their prized chest muscles", "M. Navratilova follows Haas' \"Eat to Win\" formula by loading up on these before a match"], ["a 10K", "Jane Fonda", "pecs", "carbohydrates"]], ["hats", ["Cold & wet conditions led him, in 1865, to make the \"hat that could tame the American West\"", "Slang for a construction worker", "It can top off a pen, radiator, or baseball player", "The tall silk hat worn by Abraham Lincoln named for its resemblance to a rooftop fixture"], ["a Stetson", "a hardhat", "cap", "stovepipe"]], ["\"wrong\"", ["What a morning grump did to get that way", "Mae West film based on her play \"Diamond Lil\"", "Phone problem response, title of '48 Stanwyck film", "In Cole Porter hit, it follows \"Tho' your face is charming...\""], ["got up on the wrong side of the bed", "She Done Him Wrong", "Sorry, Wrong Number", "it\'s the wrong face"]] ];
  } else if (val == "02/23/2023") {
    dailyArr = [ ["the beatles", ["The German version of this hit is titled \"Sie liebt dich\"", "Their 1st movie", "Color of the cover of the album officially titled \"The Beatles\"", "This 1964 film, The Beatles' first, received an Oscar nomination for its musical score"], ["\"She Loves You\"", "A Hard Day\'s Night", "white", "A Hard Day\'s Night"]], ["democrats", ["The English word Democrat originally meant a republican foe of the aristocrats during this revolution", "1st Democratic President of the 20th century", "Chrysler Corp. pres. considered by some Dems. as potential V.P. material", "In '83 he defeated Jane Byrne in the primary & was elected Chicago's first black mayor"], ["the French Revolution", "Woodrow Wilson", "Lee Iacocca", "Harold Washington"]], ["initials", ["Direction when compass points WSW", "The S.P.C.A.", "This director's initials stood for David Wark", "His initials, YSL, have appeared on everything from clothing & makeup to eyeglasses"], ["west-southwest", "Society for the Prevention of Cruelty to Animals", "D.W. Griffith", "Yves Saint Laurent"]] ];
  } else if (val == "02/24/2023") {
    dailyArr = [ ["the olympics", ["Athletes from this country march into the stadium first", "Fittingly, this country was the site of the first modern Olympics in 1896", "This Norwegian won the women's figure skating gold medal in 1928, 1932 & 1936", "The platform in this event is 10 meters or 33 feet above the water"], ["Greece", "Greece", "Sonja Henie", "Diving"]], ["1960", ["\"Liberated\" females were popping Enovid, 1st of these to win FDA approval", "Conductor whose movie theme arrangements include \"Moulin Rouge\" & 1960's #1 song:", "=", "After a record 8 stays of execution, this author of \"Cell 2455 Death Row\" was finally executed"], ["a birth control pill", "Percy Faith", "=", "(Caryl) Chessman"]], ["tv trivia", ["Bing Crosby's company produced this sitcom set in Stalag 13 during WWII", "Of Kukla, Fran, & Ollie, the one with just 1 tooth", "When we took him by surprise, Allen Funt told us he'd done 840 shows in this series", "After being fired from WJM-TV, this character became City Editor of the Los Angeles Tribune"], ["Hogan\'s Heroes", "Ollie", "Candid Camera", "Lou Grant"]] ];
  } else if (val == "02/25/2023") {
    dailyArr = [ ["\"mc\" names", ["He's paid to laugh at Johnny's jokes", "He \"Wanted...\" to get out of television & made \"The Great Escape\" to films", "The Smithsonian is now home to Candice Bergen's \"brother\"", "His presidential campaign won him the electoral votes of only Mass. & Washington, D.C."], ["Ed McMahon", "Steve McQueen", "Charlie McCarthy", "George McGovern"]], ["world geography", ["The Mississippi River flows more than 2,300 miles before emptying into this large body of water", "Located on the Tropic of Capricorn, this, Brazil's largest city, stays cool because of its altitude", "Abu Dhabi is the largest of the 7 states that make up this Persian Gulf country", "The mouth of this river forms Dublin Bay on Ireland's east coast"], ["the Gulf of Mexico", "SÃ£o Paulo", "the United Arab Emirates", "the River Liffey"]], ["food", ["These tiny fish are a traditional ingredient of Caesar salad & make a popular topping for pizza", "The \"breadwinner\" is also said to bring this home", "Despite its name, this cooking contest with a $40,000 grand prize is not limited to baking", "In a restaurant a flambe dessert would be served this way"], ["anchovies", "the bacon", "the Pillsbury Bake-Off", "on fire"]] ];
  } else if (val == "02/26/2023") {
    dailyArr = [ ["p's & q's", ["Goldilocks' gruel", "A TV program such as this one", "Found on some stoves & some beer drinkers", "Strategic punt on 1st, 2nd, or 3rd down"], ["porridge", "quiz (program)", "a potbelly", "a quick kick"]], ["1965", ["Astronaut Edward White was the 1st American to do this", "Carroll Baker & Carol Lynley played this '30s star in 2 movies with the same title", "As fishnet lost the fashion edge, clover leaf & patterned lace became the latest in these", "A cheating scandal created \"one heck of a roar\" at this service academy"], ["to walk in space", "Jean Harlow", "stockings", "the Air Force Academy"]], ["games", ["Boots of Butt-Kicking & the Staff of Napalm are in this game that shares its name with a \"Wizard of Oz\" folk", "In \"Going on a Trip\", what you might say if the player before you is \"taking an apple & a book\"", "In this game the \"scotch\" refers to a line", "This milkcap game that's sweeping the world derives its name from a tropical juice drink"], ["Munchkin", "apple, book & C word", "Hopscotch", "Pog"]] ];
  } else if (val == "02/27/2023") {
    dailyArr = [ ["'40s trivia", ["New transmission system for radio which began in 1940", "Profession of Johnny Longden & Eddie Arcaro", "A 12/15/41 Army order moved it from Pasadena, CA to Durham, NC", "In 1948 this city's mayor, William O'Dwyer, submitted a $1 billion budget"], ["F.M. (frequency modulation)", "jockeys", "Rose Bowl game", "New York City"]], ["music", ["Accelerando means the music is getting faster; crescendo means it's getting this", "Number of beats to the bar in music marked 3/4 time", "If a violinist is playing in the pizzicato style he's plucking the strings with these", "This brass instrument may be fitted with valves either replacing the slide or in addition to it"], ["louder", "3", "fingers", "Trombone"]], ["fiction", ["Characters in this S.E. Hinton novel include Ponyboy, Sodapop & Two-Bit", "His \"Licks of Love\" short story collection also includes the novella \"Rabbit Remembered\"", "1st name of Defoe's bawdy heroine, or a gangster's girlfriend", "This sailor is the narrator of Herman Melville's \"Moby Dick\""], ["The Outsiders", "(John) Updike", "Moll", "Ishmael"]] ];
  } else if (val == "02/28/2023") {
    dailyArr = [ ["technology",["Coders fluent in SQL or Structured Query Language can work with information storehouses known as relational these; Oracle is famous for software that creates them","Tech pioneer Adele Goldberg helped develop a programming language used to create the first GUI, short for this, featuring icons & menus","Analyzing facial & speech patterns, soft biometrics signatures help combat these videos that can make someone appear to say things they've never spoken","CSIRO has developed technology that helps drain this gas, CH4, released by the mining of coal"],["databases","a graphical user interface","deepfakes","methane"]], ["music class",["The name of this section of an orchestra in which instruments are struck comes from the Latin for \"a beating\"","Due to his deafness, he last performed in public in 1814","Instrumental, not vocal music is on offer with this type of classical work; Beethoven's \"Moonlight\" one is pretty good","It's a moderate tempo, faster than adagio but slower than allegretto"],["percussion","(Ludwig Van) Beethoven","a sonata","andante"]] , ["math",["The set of positive & negative whole numbers & zero is the set of these","\"You can't share 10 apples equally among no people\" is one way to teach kids that this process is against math rules","Usually symbolized by a letter, a changing quantity in algebra is called this","The 6 functions of this branch of math are each defined by the ratio of 2 sides in a right-angled triangle"],["integers","dividing by zero","a variable","trigonometry"]] ];
  } else {
    dailyArr =  [ ["Ranks & Titles",["Going down the ranks of the Royal Navy, remember your 3 C's: commodore, captain, this","As one of these enlisted ranks in the army, your grade is E-1 or E-2; as a first class one, it's E-3","Latin for \"to earn by service\", this honorary title often follows the name of a retired college professor","Title for the sovereign prince of Austria's royal family; Francis Ferdinand was one"],["commander","private","emeritus","Archduke"]], ["Cooking",["Butterball advises putting the thermometer in this part of the turkey that provides dark meat","Hungarian goulash recipes measure salt & pepper in teaspoons or tablespoons, but this spice in cups","Also sometimes done to harbors, it means to coat food with a dry ingredient like flour","Ricotta isn't a cheese, it's a cheese by-product made from this liquid drained from cheeses"],["the thigh","paprika","dredge","whey"]] , ["Number Please",["Number of toes on each front paw of most cats","Decennoval refers to this number that's also the atomic number of potassium","In baseball, the sum of balls & strikes represented by a full count","The word myriad can refer to any large number of things, or specifically to this big number"],["5","19","5","10,000"]] ];
    // Template dailyArr = [ ["cat0",["q0","q1","q2","q3"],["a0","a1","a2","a3"]], ["cat1",["q0","q1","q2","q3"],["a0","a1","a2","a3"]] , ["cat2",["q0","q1","q2","q3"],["a0","a1","a2","a3"]] ];
  }
}
