function getDailyQuestions(val) {
  var startDate = new Date("01/17/2023");
  var endDate = new Date(val);
  iteration = ((endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)) + 1;
  
  if (val == "01/17/2023") {
    daily0 = ["Metals",["The Statue of Liberty is sheathed in more than 31 tons of this metal mined in Norway", "Discovered in Colorado in the 1950s, coffinite is an ore that is more than 60% this radioactive metal","An oxide of this light metal, discovered in 1791, is used extensively as a white pigment","This metal used to make semiconductors was discovered by Clemens Winkler & named for his homeland"],["Copper","Uranium","Titanium","Germanium"]];
    daily1 = ["The Revolutionary War",["The British passed the Intolerable Acts to punish Massachusetts for this event","General Richard Montgomery was killed December 31, 1775 leading a hopeless attack on this Canadian city","Born in Connecticut, Nathan Hale was a graduate of this Ivy League university","In the 1760s painter Charles Willson Peale joined this patriot group, angering Loyalist creditors"],["Boston Tea Party","Quebec","Yale","Sons of Liberty"]];
    daily2 = ["Lakes & Rivers",["Famous for its monster, it forms part of the Caledonian Canal","At 2,485 miles, the Parana is this continent's second-longest river","This largest lake in Africa is also the main reservoir of the Nile River","The pre-Incan Uros people still inhabit floating islands high in the Andes in this lake"],["Loch Ness","South America","Lake Victoria","Lake Titicaca"]];
  } else if (val == "01/18/2023") {
    daily0 = ["Car Talk",["When fixing cars, \"R & R\" means remove & do this to an auto part","This converter reduces the level of harmful pollutants in a car's exhaust","Manual shifters used to come in \"4 on the floor\" & \"3 on\" this arboreal word for the steering column","Inspect the master cylinder, part of the hydraulics sending fluid through the lines for this drum or disc system"],["restore (or replace or repair)","a catalytic converter","tree","the brakes"]];
    daily1 = ["Biology",["Stomata, leaf pores that take in this gas, enlarge when its level in the air drops below normal","This 3-letter suffix denotes a carbohydrate, especially a sugar","There are 3 main types of these in the body--smooth, striated & cardiac","This part of the small intestine is named for the fact that it's about as long as the width of 12 fingers"],["carbon dioxide","-ose","muscles","duodenum"]];
    daily2 = ["5-Letter Words",["To surpass, or a Microsoft spreadsheet program","Honey is an animal product & can be excluded from a strict this type of diet","A musical composition with a repeated theme using multiple voices, or a disturbed state of altered consciousness","The Carabao is a popular variety of this tropical fruit"],["excel","vegan","fugue","mango"]];
  } else if (val == "01/19/2023") {
    daily0 = ["Communication",["56' wide & 29' high, a digital billboard called the Broadway Spectacular is in the heart of this New York City area","With a brain larger than man's, their language is a system of beeps, whistles, & clicks","The 2-way field radio developed by Don Hings for bush pilots in 1937 soon got this snappier name","France's Robert Coulondre, who had this job, presented a futile demarche, a diplomatic note, in Berlin Sept. 1, 1939"],["Times Square","dolphins","walkie-talkies","ambassador to Germany"]];
    daily1 = ["Mississippi",["On Jan. 9, 1861, Mississippi became the 2nd state to do this","In 1898 in Biloxi, Edward Barq began bottling & selling this beverage","He modeled his fictional Yoknapatawpha County on the area around his hometown of Oxford","Over 55% of the land in Mississippi is covered by these"],["secede from the Union","root beer","(William) Faulkner","forests"]];
    daily2 = ["Vocabulary",["If you're piscivorous, you eat this, which can \"net\" you some health benefits","Latin gets its name from \"Latium\", a region of this country","Sometimes it's a pickled flower bud used as a garnish, & sometimes it's a prank or theft","From the Latin for \"earth\", it's another word for patio"],["fish","Italy","a caper","terrace"]];
  } else if (val == "01/20/2023") {
    daily0 = ["Weather",["On a weather map, 3 horizontal & parallel lines indicate this weather condition","From the Middle English for \"fall of dew\", it's a light rain in which the water droplets are less than .5 mm in diameter","Non-fluid aneroid barometers use a partial one of these instead of mercury to measure air pressure","The highest known barometer reading in the U.S., 31.85, was recorded in this state during a 1989 cold wave"],["fog","drizzle","vacuum","Alaska"]];
    daily1 = ["American History",["He died in 1804 the day after his duel with Aaron Burr","Without the knowledge of Congress, James Madison took possession of West Florida from this country","In the 1850s this state was \"Bleeding\" as pro- & anti-slavery forces met up in a preview of the Civil War","The \"separate but equal\" doctrine in the case of Plessy v. this judge upheld racial segregation for almost 60 years"],["Alexander Hamilton","Spain","Kansas","Ferguson"]];
    daily2 = ["Old Testament",["\"And the Lord spake unto the fish and it vomited out\" him \"upon the dry land\"","In the 1st month of their 2nd year in the desert, Moses & the people celebrated this holiday","Leviticus 13 is a symptom guide for this skin disease you hear a lot about in the Bible","Isaiah & Jeremiah are considered major ones, Obadiah & Zechariah, minor"],["Jonah","Passover","leprosy","prophets"]];
  } else if (val == "01/21/2023") {
    daily0 = ["Spiders",["Each of a spider's these contains 7 segments, so that's 56 segments per spider","The spider family Uloboridae lacks these glands, so if you want a pet spider, maybe get one of them","Many garden spiders are among those classed as these \"weavers\" of round webs","1 of the world's most dangerous spiders is this country's Sydney funnel web"],["legs","venom","orb weavers","Australia"]];
    daily1 = ["Europe",["This country that has many satellites built a monument to its 1st satellite","Rossini never visited this Spanish city where he set an 1816 opera","This is the largest & southernmost of the Baltic republics","Bonny Ben Nevis, highest peak in the United Kingdom is in this country"],["Russia","Seville","Lithuania","Scotland"]];
    daily2 = ["Golf",["Bird word for 2 under par on a hole","The \"pitching\" this type of club is used for short, lofted shots","The closely mowed ring of grass around a putting green is called an apron or this out-there name","Exhibiting Bernoulli's Principle, these indentations on a golf ball cause it to lift & stabilize it in flight"],["an eagle","wedge","the fringe","a dimple"]];
  } else if (val == "01/22/2023") {
    daily0 = ["Rock 'N Roll",["In \"American Pie\", Don McLean drove this to the levee","The concert theatrics of this band included Pete Townshend smashing his guitar to bits","Peter & Gordon's hit, \"World Without Love\", was written by this Beatle pair","In 1985, Tears for Fears said \"everybody wants to\" do this"],["Chevy","The Who","Lennon & McCartney","rule the world"]];
    daily1 = ["Pop Music",["Ariana Grande sings, \"When all is said & done, you will believe\" this, a 2018 song that mixes spirituality & female power","A song by Zedd, Maren Morris & Grey asks, \"Oh baby, why don't you just meet me in\" this title place","In 2015 Zayn Malik officially quit this band","\"Somebody Told Me\" that The Killers were formed in this city in 2002"],["\"God Is A Woman\"","the middle","One Direction","Las Vegas"]];
    daily2 = ["Opera",["This opera ends with the title madam committing hara-kiri","Don Jose is bewitched by this title gypsy girl","Mozart opera in which the count tries to thwart & postpone his valet's wedding","Peter Cornelius' opera \"The Barber of Baghdad\" was based on a tale in this collection"],["Madame Butterfly","Carmen","The Marriage of Figaro","Arabian Nights"]];
  } else if (val == "01/23/2023") {
    daily0 = ["Cats",["An old name for Thailand is in the name of this breed that sometimes has crossed eyes","Shorthaired cats were derived from the caffre cat, which was domesticated by this ancient civilization","In the 1960s officials of the Ankara, Turkey zoo saved this pure breed from extinction","Kittens have 26 of these, adult cats 30"],["a Siamese","Egypt","the Turkish Angora","teeth"]];
    daily1 = ["Food Facts",["This word was once used for the meat of any hunted animal; now it refers to deer meat","A genoise is a light sponge cake whose name is derived from this city","Mostly made from the whites, egg substitutes don't contain fat or this artery-clogging lipid","Cannellini is a white kidney bean, cannelloni is a type of this"],["venison","Genoa","cholesterol","pasta"]];
    daily2 = ["Medicine",["The A1C test measures average blood sugar over the past 3 months; at 5.7% you're pre-this, at 6.5 you're this","In this \"effect\" people are given inert substances & seem to improve","Named for an American surgeon, McBurney's incision is a cut in the lower right abdomen used when removing this","Often found in areas with large deer populations, this bacterial inflammatory disease was first identified in 1975"],["diabetic","placebo","the appendix","Lyme disease"]];
  } else if (val == "01/24/2023") {
    daily0 = ["Flags",["Fiji's flag depicts many of its tropical treasures, including sugar cane, bananas & this type of palm","The diamond shape on its flag references the fact that it was the only diamond-producing U.S. state","The fortress on the flag of this British overseas territory symbolizes its strategic importance on the Mediterranean","The blue & white in Somalia's flag were influenced by the flag of this body that has played a role in Somali history"],["a coconut tree","Arkansas","Gibraltar","the United Nations"]];
    daily1 = ["Children's Literature",["Sketches written for Punch became his first novel, \"Lovers in London\"; Winnie-the-Pooh came 21 years later","\"One Sunday morning the warm sun came up and--pop!--out of the egg came\" this title larva","A young rabbit gets ready for bed in this classic by Margaret Wise Brown","Thing One & Thing Two are characters in this 1957 Seuss classic"],["(A.A.) Milne","the Very Hungry Caterpillar","Goodnight Moon","The Cat in the Hat"]];
    daily2 = ["Animal Adjectives",["Vulpine, like the bat-eared or the crab-eating","Ostracean, like the Olympia or the pearl","Anserine, like the snow or the nene","Columbine, like the rock or the mourning"],["the fox","an oyster","a goose","a dove"]];
  } else if (val == "01/25/2023") {
    daily0 = ["Mathematics",["The exact value of this, the ratio of a circle's circumference to its diameter, can't be written down","This type of \"strip\", a continuous flat loop with 1 twist, has only 1 surface","In Roman numerals, the largest number represented by a single letter with no markings","A set with no elements is described as this"],["pi","a Möbius strip","1,000 (the letter M)","Null / empty"]];
    daily1 = ["Science",["Every second, fusion reactions in the Sun convert about 600 million tons of this element into helium","Newly created nihonium is classified as a \"trans-\" this element","During a total solar eclipse, you can glimpse this \"colorful\" layer of the Sun just above the photosphere","First predicted in 1930, this particle with no charge goes through miles of matter without reacting with a proton or neutron"],["hydrogen","transuranium","the chromosphere","neutrinos"]];
    daily2 = ["History",["An international force seized Beijing on August 14, 1900, crushing this rebellion","Name of the king who after beating Rome at Asculum but taking heavy casualties, said one more such win would undo him","In 1950 & then again in 1951, this capital city fell to invading forces who were evicted each time by U.N. troops","The USA's worst depression before the Civil War began with what's usually called this event \"of 1837\""],["the Boxer Rebellion","Pyrrhus","Seoul","the Panic"]];
  } else if (val == "01/26/2023") {
    daily0 = ["Geography",["Lahore, this country's second-largest city, is the capital of the Punjab province","This Italian region that includes Pisa & Florence gets its name from the Etruscan people","If you're on Nevis & have business at Government House, you need to go to this nearby island","Afrikaner Gert Alberts was the leader of a famous crossing of this desert in the 1870s"],["Pakistan","Tuscany","St. Kitts","the Kalahari Desert"]];
    daily1 = ["Languages",["Standard Chinese is based primarily on this form of Chinese spoken by the educated in Beijing","This language is spoken by about 11 million in Europe & about 200 million in South America","L.L. Zamenhof grew up in an area of Poland where 4 languages were spoken, leading to ethnic animosity, so he created this","The language of this small Balkan country has 2 main dialects: Gheg & Tosk"],["Mandarin","Portugese","Esperanto","Albania"]];
    daily2 = ["Constellations",["The brightest star in Bootes is this color giant & is 100 times more luminous than the sun","With this constellation winding around it, Ursa Minor must hope it isn't fire-breathing","The Pup is the companion to this star in Canis Major","This constellation's second-brightest star, Shaula, is also known as \"the Stinger\""],["red","Draco","Sirius (the Dog Star)","Scorpio"]];
  } else if (val == "01/27/2023") {
    daily0 = ["Dragons",["In this novel, Bilbo Baggins, Gandalf & 13 dwarves reclaim Lonely Mountain & its riches from the dragon Smaug","In Babylonian myth, the dragon Tiamat's upper half becomes Heaven; the lower half, this","This Scandinavian prince rid the Danes of the monster Grendel; 50 years later he was killed by a dragon","Last name of King Arthur's father Uther, derives from the Welsh, meaning \"head\" or \"chief\""],["The Hobbit","the earth","Beowulf","Pendragon"]];
    daily1 = ["Farming",["Driving 20-ton vehicles on farmland can mean that the next year you'll get \"stuck in\" one of these, defined as a wheel track 3\" deep","In July 2019 dozens of farmers of these beans went to congress, demanding a deal be made to resume trading with China","Heinz sauces--er, sources--ketchup tomatoes from this state's vast & fertile Central Valley","Applied to farmland, it means left without sowing for a period in order to restore its fertility"],["a rut","soybeans","California","fallow"]];
    daily2 = ["Guinness Records",["Takabisha, the steepest one of these, has a free-falling angle of 121 degrees; your move, Space Mountain","Talk about a special day! Romanian model Ema Dumitrescu's wedding dress had a 1.85-mile-long one of these","A 1759 document records Arthur Guinness signing a 9,000-year lease on a brewery at St. James' Gate in this city","In 2004, Tia, a mastiff, gave birth to the largest litter of these ever--24"],["a rollercoaster","a train","Dublin","puppies"]];
  } else if (val == "01/28/2023") {
    daily0 = ["Words",["This name for a work of art that you may carve in art class comes from the Latin for \"to carve\"","The name of these small towers often seen on castles comes from Old French for \"small towers\"","This word for a white wine & soda drink first appeared in Webster's in 1961","A harsh expression substituted for a more neutral one is a dysphemism & this is the opposite"],["sculpture","turrets","spritzer","euphemism"]];
    daily1 = ["Chemistry",["The lipids, which include fats & oils, are organic compounds that don't appreciably interact with this","Relative atomic mass is another name for this","Acids & bases are among these current conductors; using a solid instead of a liquid one reduces the risk of fire in batteries","This brown pigment of hair, skin & eyes is a polymer"],["water","atomic weight","electrolytes","melanin"]];
    daily2 = ["Games",["Each player is dealt 26 cards in this game; if both players turn up a card of the same rank, it's this, the name of the game","In the game of Hearts, this card is known as \"The Black Lady\"","Join in & tell us that this is the lowest-rated suit in contract bridge","In U.S. croquet, a ball that goes through all the wickets has this travelling name, especially if it's the red one"],["War","the queen of spades","clubs","a rover"]];
  } else if (val == "01/29/2023") {
    daily0 = ["Fitness",["Sprinting & powerlifting are examples of this type of exercise that means \"without oxygen\"","Referring to exercise that raises your heart rate and gets your blood flowing, \"cardio\" is short for this","To improve balance, try this ancient exercise with a Chinese name that means \"supreme ultimate fist\"","It's the \"electrical\" term for the amount of weight or pressure involved in an exercise"],["anaerobic","cardiovascular","tai chi","resistance"]];
    daily1 = ["Ancient Rome",["The last emperor of Rome, who was overthrown in 476, shared his name with this legendary founder of the city","Carved on stone or metal, the acta diurna was an early newspaper posted this often in a public area","Roman roads were built with concrete made from pozzolana, ash from these; the roads by Pompeii must've been good","Latin for \"father of the family\", he was the oldest living male of the family & had total control of his household"],["Romulus","daily","volcanoes","pater familias"]];
    daily2 = ["Plants",["In 2006 the city of L.A. Iimited its planting of this tall tree because it's disease-prone, non-native & gives little shade","Archaeologists have found that varieties of this grain, like Emmer & Einkorn, were grown in the 7th millennium B.C.","Fungi not only lack roots, stems & leaves, but also this food-making matter","This tree's name comes from the Hindi word for \"trader\" because people displayed their wares in its shade"],["the palm","wheat","chlorophyll","the banyan tree"]];
  } else if (val == "01/30/2023") {
    daily0 = ["Fictional Characters",["She is the narrator of \"To Kill a Mockingbird\"","This character in \"The Legend of Sleepy Hollow\" is said to be the ghost of a Hessian trooper","As this book begins, Santiago had \"gone eighty-four days... without taking a fish\"","For stealing a loaf of bread during the French Revolution, he ended up serving 19 years"],["Scout (Jean Louise Finch)","the Headless Horseman","The Old Man and the Sea","Jean Valjean"]];
    daily1 = ["Starts With \"A\"",["The Rhode Island Greening is a tart one of these you can use to make tarts","Dappled horse believed to have descended from wild mustangs in Nez Perce territory","Richard the Lion-Heart was duke of this French area that his mother Eleanor had inherited","From the Latin word for \"tree\", it's a place where many kinds of trees & plants are exhibited"],["an apple","an appaloosa","Aquitaine","arboretum"]];
    daily2 = ["Alphabet Soup",["T is for this soup that's paired with grilled cheese on the Campbell's Kitchen website","B is for this thick 6-letter soup, perhaps lobster or mushroom","A is for this spicy Mexican soup whose name is Spanish for \"meatball\"","\"F\" is for this soup with a little cheesy goodness on top"],["tomato","bisque","albondigas","French onion soup"]];
  } else if (val == "01/31/2023") {
    daily0 = ["20th Century America",["Its 1980 eruption was the first by a volcano in the continental U.S. outside Alaska since 1917","In 1954 Senator Joe McCarthy provoked televised hearings after accusing the army of \"coddling\" these people","This first Disney animated feature had its world premiere on December 21, 1937","Tragically, on January 28, 1986 this exploded 73 seconds after liftoff"],["Mount St. Helens","communists","Snow White and the Seven Dwarfs","the Challenger"]];
    daily1 = ["Birds",["Perhaps this \"thrush\", a type of babbler, hangs out at comedy clubs with the same-named hyena","During mating season the male ruff develops a large frill of feathers around this body part","From the elaborate dwellings wrens build, their Latin family name is this, meaning \"cave-dweller\"","The gray jay is not as famous as this relative whose scientific name is Cyanocitta cristata"],["laughing thrush","neck","Troglodytes","the blue jay"]];
    daily2 = ["Italian Art",["Lesser known works by this Italian master include \"The Virgin Of The Rocks\" & \"The Adoration Of The Magi\"","Dazzling works by Bernardo Strozzi of Genoa include one of this woman's \"Annunciation\"","One of the greatest painters of the Venetian school, this 16th century artist was born Tiziano Vecellio","Circa 1415, Donatello carved a marble relief of this man slaying a dragon"],["Leonardo da Vinci","Mary","Titian","St. George"]];
  } else if (val == "02/01/2023") {
    dailyArr = [ ["Water",["Hydrolysis uses water to destroy these that hold a compound together","Water has low this \"V\" property, meaning it's quick to flow or change shape","Usually using zeolite or an ion-exchange resin, this process removes minerals from water","Known to the ancients, these wells are named for a French province where they were 1st drilled c. 1100"],["bonds","viscosity","water softening","artesian"]], ["Early Man",["790,000-year-old flints from a site in Israel provide the oldest known evidence of early man's control of this","Around 11,000 B.C. people in Greece sailed over 70 miles to Melos to get this volcanic glass for tools","The enlarged brain of this early human species helped it become the longest-lived member of the human family tree; named for its upright posture, it survived nine times longer than our species has been around","The Chalcolithic Age is named for this, the 1st metal discovered by man"],["fire","obsidian","homo erectus","copper"]], ["Literary Quotes",["He \"Appeared on the sidewalk with a bucket of whitewash and a long-handled brush\"","This title character: \"On the first of September 1651, I went on board a ship bound for London\"","In this Poe story, \"I had scarcely stepped from my... bed of horror... when the motion of the hellish machine ceased\"","In a Hans Christian Andersen story, an old woman tells her that her beautiful tail is \"thought on Earth to be quite ugly\""],["Tom Sawyer","Robinson Crusoe","The Pit and the Pendulum","the Little Mermaid"]]];
  } else if (val == "02/02/2023") {
    dailyArr = [ ["Hobbies",["A life list (which might include auks) & binoculars are used in this hobby","Collecting coins can be lucrative if you have one from 44 B.C. minted by Marcus Mettius showing this Roman","At the Merseyside Maritime Museum, Des Newton would delight kids by showing how to make these impossible-seeming models","Settle in with some needlework & crochet this cozy blanket that gets its name from the land of the Pashtun people"],["birdwatching","Julius Caesar","ships in a bottle","afghan"]] , ["In the Dictionary",["A Biblical woman's name, it means pity but is usually found before \"-less\" to mean pitiless","This word for the animals of a particular region is from the Latin","It's defined as any substance with the tendency to produce a cancer","It's the long word specifically for a 150th anniversary"],["ruth","fauna","a carcinogen","a sesquicentennial"]] , ["Social Studies",["Bernie Sanders spent much of 2016 urging change to this 2-word Latin term for the existing state of affairs","This group is composed of those of your same age or social position; in a courtroom, you might face a jury of them","A 1951 work on this person in societies of northern Asia says he is \"magician and medicine man... priest, mystic and poet\"","This social science focuses on the characteristics of human populations such as size, growth & distribution"],["the status quo","peers","a shaman","demography"]] ];
  } else if (val == "02/03/2023") {
    dailyArr =  [ ["Ranks & Titles",["Going down the ranks of the Royal Navy, remember your 3 C's: commodore, captain, this","As one of these enlisted ranks in the army, your grade is E-1 or E-2; as a first class one, it's E-3","Latin for \"to earn by service\", this honorary title often follows the name of a retired college professor","Title for the sovereign prince of Austria's royal family; Francis Ferdinand was one"],["commander","private","emeritus","Archduke"]], ["Cooking",["Butterball advises putting the thermometer in this part of the turkey that provides dark meat","Hungarian goulash recipes measure salt & pepper in teaspoons or tablespoons, but this spice in cups","Also sometimes done to harbors, it means to coat food with a dry ingredient like flour","Ricotta isn't a cheese, it's a cheese by-product made from this liquid drained from cheeses"],["the thigh","paprika","dredge","whey"]] , ["Number Please",["Number of toes on each front paw of most cats","Decennoval refers to this number that's also the atomic number of potassium","In baseball, the sum of balls & strikes represented by a full count","The word myriad can refer to any large number of things, or specifically to this big number"],["5","19","5","10,000"]] ];
  } else {
    dailyArr =  [ ["Ranks & Titles",["Going down the ranks of the Royal Navy, remember your 3 C's: commodore, captain, this","As one of these enlisted ranks in the army, your grade is E-1 or E-2; as a first class one, it's E-3","Latin for \"to earn by service\", this honorary title often follows the name of a retired college professor","Title for the sovereign prince of Austria's royal family; Francis Ferdinand was one"],["commander","private","emeritus","Archduke"]], ["Cooking",["Butterball advises putting the thermometer in this part of the turkey that provides dark meat","Hungarian goulash recipes measure salt & pepper in teaspoons or tablespoons, but this spice in cups","Also sometimes done to harbors, it means to coat food with a dry ingredient like flour","Ricotta isn't a cheese, it's a cheese by-product made from this liquid drained from cheeses"],["the thigh","paprika","dredge","whey"]] , ["Number Please",["Number of toes on each front paw of most cats","Decennoval refers to this number that's also the atomic number of potassium","In baseball, the sum of balls & strikes represented by a full count","The word myriad can refer to any large number of things, or specifically to this big number"],["5","19","5","10,000"]] ];
    // Template dailyArr = [ ["cat0",["q0","q1","q2","q4"],["a0","a1","a2","a4"]], ["cat1",["q0","q1","q2","q4"],["a0","a1","a2","a4"]] , ["cat2",["q0","q1","q2","q4"],["a0","a1","a2","a4"]] ];
  }
}
