var allCats = ["GARDENS","EGYPT","U.S. GEOGRAPHY","AUTOMOBILES","SILLY SONGS","CURRENT EVENTS","ROCK 'N ROLL","HERALDRY","1885","U.S. STATES","COMIC CATS & DOGS","RITUALS","HAVE A \"HART\"","4-LETTER WORDS","FIRST LADIES","WINTER SPORTS","CANADA","U.S. CITIES","FOODS","\"T\" TIME","INSECTS","50TH ANNIVERSARIES","PEOPLE","HOWDY DOODY","POLITICS","WORD ORIGINS","INDIA","MOVIE COMPOSERS","ALL NUMBERS","GOVERNORS","WEATHER","YOU GET A \"D\"","SHIPS","SCOTLAND","4-WORD PHRASES","GEOGRAPHY","GENERALS","AUSTRALIA","ODD JOBS","SPORTS","WEAPONS","SPORTS TRIVIA","MOVIE MOTTOS","MOVIES","TRIVIA","FAMOUS PIGS","HUNTING","BUTLERS","CHEMISTRY","THE '20S","WILD WEST","ASTRONOMY","U.S. BEACHES","LETTER PERFECT","STUFFED","FOOTBALL","POP MUSIC","COOKING","COUNTRY MUSIC","WELCOME TO THE U.N.","DOUBLE MEANINGS","NUTS","STARTS WITH \"OO\"","THE '30S","FOREIGN CUISINE","1933","POP QUIZ","ANATOMY","EASY MATH","OLD TESTAMENT","HISTORY","IN THE MIDDLE","\"BEN\"","1960","WORD PLAY","TRAINS","WEIGHTS & MEASURES","TREES","POTENT POTABLES","FASHION","THE '50S","QUOTE, UNQUOTE","\"BROWNS\"","WHALES","ODD WORDS","DANCE FEVER","BASEBALL","THE OLYMPICS","NATURE","FOOD FACTS","KID STUFF","CRIME & PUNISHMENT","SUDDEN DEATH","COLORS","\"ON\" WORDS & \"UP\" WORDS","ZOOLOGY","HIGHWAYS & BYWAYS","VIRGINIA","TV TRIVIA","ASIA","\"CAT\" EGORY","MILITARY TELEVISION","WHITE HOUSE TRIVIA","LEAPS & JUMPS","FAIRIES","GANGSTER MOVIES","SEASONINGS","ROCK RECORDS","BEN FRANKLIN","SCIENCE","AFRICA","WATER SPORTS","MOVIE TRIVIA","'40S TRIVIA","BOXING","DOUBLE M","LADIES IN SONG","\"AC\"/\"DC\"","LAKES & RIVERS","PETS","\"WRONG\"","1945","WASHINGTON D.C.","SHAPING UP","THE \"IN\" CROWD","THE '60S","GYMNASTICS","ALL THAT JAZZ","INVENTIONS","TIME","USED-UP CARS","RUSSIAN HISTORY","PLAYWRIGHTS","AMERICAN REVOLUTION","SITCOMS","VEGETABLES","SPORT OF KINGS","\"B\" THERE","DINING OUT","FAIRY TALES","MIRACLES","\"MC\" NAMES","COMEDIANS","CHILD STARS","UP IN \"ARM\"S","FICTION","POE","A","BRAZIL","P'S & Q'S","ROARING '20S","1965","TWINS","WORLD GEOGRAPHY","STARTS WITH \"C\"","STARTS WITH \"B\"","ISLANDS","GAY BLADES","POLITICAL QUOTES","DEMOCRATS","U.S. HISTORY","THE BEATLES","FIRST AID","SONGS","FISH","JAPAN","DEAR JOHNS","FOOD","CARS","SAINTLY CITIES","SUPER HEROES","\"ANDY\"","'60S TRIVIA","ANCIENT WORLDS","HOLLYWOOD LEGENDS","\"HARD\"","GLASS","NUMBER PLEASE","A LA \"CART\"","GAMES","SPORTS QUOTES","ROAD WORK","MAGAZINES","FOLK MUSIC","PRISON SONGS","AWARDS","GRAMMAR","MUSIC","STATE CAPITALS","6-LETTER WORDS","PRESIDENTIAL FIRSTS","BUSINESS & INDUSTRY","COLORFUL GEOGRAPHY","ITALY","FIRST NAME BASIS","\"MARCH\" ON","BALLET","1984","STARTS WITH \"A\"","BOATS","HATS","TELEVISION","GEMS","FORMER OCCUPATION","INITIALS","THE '40S","NURSERY RHYMES","BRITISH ISLES","CABLE TV","MELS","B","C","E","F","D","CHANNELS","\"SHELLS\"","FAST FOOD","THE HOME","LANDMARKS","FEATHERED FRIENDS","EASY LISTENING","SWAMP THINGS","BEST SELLERS","CORPORATE AMERICA","BIRDS","WORLD SERIES","BODIES OF WATER","KIDDIE LIT","LOUISIANA","\"JACKS\" OF ALL TRADES","RADIO","KANSAS","PRESIDENTS","OCEANS","1956","1953","TAXES","\"TOASTS\"","CHEWING GUM","THE WHITE HOUSE","THE OLD TESTAMENT","HOT MOVIES","\"FIRE\"","BRIDGES","1968","RACY LADIES","3-LETTER WORDS","DYNASTIES","ABOUT \"FACE\"","1959","TOUCHDOWN TOPICS","TRADE NAMES","11-LETTER WORDS","SPACE","ROYALTY","TRANSPORTATION","\"FRIDAYS\"","BROADWAY","HOUSEHOLD HINTS","SPAIN","TABLE MANNERS","BEGINS WITH \"L\"","FACTS & FIGURES","RELATIVES","\"B\" MOVIES","NEWSCASTERS","OUTLAWS","ADDRESSES","DOUBLE TALK","EDUCATION","GAY '90S","\"UPS\" & \"DOWNS\"","CALIFORNIA","THE FLINTSTONES","THE 1970S","STATES IN SONG","RELIGION","LEGENDS","MYSTERIES","20TH CENTURY ART","CATS","MONEY","FLOWERS & TREES","NONPOTENT POTABLES","JUST NAMES","GOLF","OSCAR SONGS","ACTORS & ROLES","HOLIDAYS","PEACE","SINGERS & DANCERS","NEW HAMPSHIRE","JARGON","TRIOS","\"CAN\" IT","MUSIC ON THE MAP","HOMONYMS","LEFTOVERS","CARTOONS","THE COMICS","VACATION SPOTS","BOWLING","WORLD CAPITALS","LITERARY QUOTES","THE BULL PEN","SIR! YES SIR!","STARTS WITH \"N\"","SINGERS & SONGS","AUGUST","WW II AVIATION","BROTHERS GRIMM","SOUTH AMERICA","FASHION HISTORY","\"HALL\"S","TRENDS","BY THE NUMBERS","ROCK ÂN ROLL","AMERICAN LITERATURE","STARTS WITH \"H\"","STARTS WITH \"Q\"","TOYS & GAMES","MOVIE MAMMALS","THE KENNEDYS","THE AIR FORCE","12S","MOSCOW","PENNSYLVANIA","AMERICAN INDIANS","MYTHOLOGY","FAMOUS DUNCANS","BOTANY","CITIZENSHIP TEST","RATED \"EX\"","EASY SCIENCE","TALK LIKE THE ANIMALS","MUSICAL NIGHTS","UTAH","MARXISMS","IN OTHER WORDS","BICYCLES","MONOPOLY","BOUNCE","LANGUAGE","1976","INFANCY","HORSES","COMMUNICATION","BOTANICAL SONGS","3","FOOD TRIVIA","TRADE CENTERS","PSYCHOLOGY","BUSINESSMEN","TV GALS","THE EARTH","IDAHO","COINS","TOP 40","ANCIENT AMERICA","GARDENING","TECHNOLOGY","THE FOOD STORE","WEDDINGS","4","LABOR","STUPID ANSWERS","SEA LIFE","ENDS IN \"OO\"","IN THE KITCHEN","2","FRUITS","MEDICINE","ELECTRONICS","\"C\" WORDS","CLOCKS","ALL KINDS OF RED","BEER","TRAVEL U.S.A.","LITERATURE","1958","TAX FACTS","'60S BRITISH ROCK","\"SEA\" WORDS","GIRLS IN SONG","STARTS WITH \"D\"","FAMOUS NAPOLEONS","AVIATION","OLD RADIO","\"LITTLE\" SONGS","NAMED FOR","GREECE","MILITARY MEN","\"MOON\"S","WAYS & MEANS","NO NO'S","5","\"LONG\" SONGS","1","MINERALS","RIVER SONGS","ASTRONOMICAL SONGS","TOYS IN SONG","PUMPKINS","5-LETTER WORDS","RULERS","ENDS IN \"ID\"","TRUCKS","PATRON SAINTS","DETECTIVE FICTION","G.W. CARVER","DOGS","MYSTERIOUS EAST","HOLLYWOOD","TENNIS","COMMOND BONDS","\"GRAND\"","CHICKENS","GAME SHOWS","COMIC STRIP DOGS","BREAD","ROBIN HOOD","ETIQUETTE","MEDAL OF HONOR WINNERS","20TH CENTURY","6","\"K\" ON THE MAP","GERMANY","CLASSICAL MUSIC","\"LINE\"S","\"COCK\" A DOODLE DO","ASTROLOGY","AROUND THE HOUSE","SPORTS DATES","PETROLEUM","\"BLACK\"","YOUNG STARS","SCIENCE & NATURE","MOVIE ANIMALS","STATE BIRDS","COOKING TERMS","LEFT & RIGHT","SONGS WITH \"HEART\"","DISNEY","NICKNAMES","PRESIDENTIAL TRIVIA","KNOTS TO YOU","MINI-COUNTRIES","20TH CENTURY AMERICA","GAMBLING","CASABLANCA","THE LONGEST","POLITICAL TRIVIA","CHOCOLATE","#1 SONGS","\"LIFE\"","WE CAN BE HEROES","VERMIN","MUSICAL MONTHS","METALS","\"UPPER\"S","MEDICAL TRIVIA","AMERICAN FOOD AND DRINK","'70S MOVIES","BEASTLY QUOTES","WHAT'S \"UP\" DOC","MODERN HISTORY","\"TIME\"LY SONGS","HARDWARE STORE","MUSICAL ANATOMY","JUST DESSERTS","THE LAW","MEDICAL FOLKLORE","ADVERTISING SLOGANS","FAMOUS \"VAN\"S","FAVORITE PASTIMES","HEAVEN","NEWSPAPERS","UNREAL ESTATE","GOLDEN OLDIES","CARS IN SONG","JEWELRY","TRIPLE TALK","CARDS","LIGHTNING","\"F\" WORDS","AGES","LAWS & RULES","FIRSTS","COMPLETE A PHRASE","NAME CHANGES","EARLY MAN","WORMS","ODDS & ENDS","ART","\"SICK\"","BRITISH CLOTHING","FAIRIES & WEE FOLK","NUMBERS","BOTTOMS UP","NOTORIOUS WOMEN","AUTOMOBILE TRIVIA","SPORTS MOVIES","MUNCHY MOVIES","WAR STORIES","SAILING","WORLD HISTORY","HOTELS","SOUTHERN COOKING","MUSICAL INSTRUMENTS","\"ROCKY\"S","THE HUMAN BODY","ILLINOIS","GOVERNMENT","NAMES","WASHINGTON STATE","GREAT \"SCOTT\"","THE 1950S","TV NEIGHBORS","\"GARDENS\"","MAYBE WE'LL INVADE BRITAIN!","WILD CATS","BOOKS & AUTHORS","THE THEATRE","THE PLANETS","STORMS","1932","\"BULL\"","PROVERBIAL ANATOMY","WOOD","\"7\" MOVIES","PARADES","DOCTORS","BANANAS","\"WIND\" WORDS","\"J\" WORDS","SODA POP QUIZ","GHOSTS","SHAKESPEARE","ÂSTREETSÂ","THE Â70S","SONGS WITH SPIRITS","POULTRY","MATH CLASS","HOMOPHONES","STARTS WITH \"Y\"","THE OSCARS","STARTS WITH ÂBÂ","PRESIDENTIAL QUOTES","WWII TRIVIA","1974","SMOKING","BEAR FACTS","POLAND","NUMBERS IN SONG","DOLLS","COMIC STRIPS","HOLLYWOOD DOGS","FEMININE FIRSTS","PLANT NAMES","FAMILIAR PHRASES","SPELLING","LAS VEGAS","MS.","12-LETTER WORDS","STARTS WITH \"M\"","FAMOUS NAMES","OPERA","MUSICAL NUMBERS","AUTOBIOGRAPHIES","BLOOD","THE 1950'S","THE HOSPITAL","O'HOLLYWOOD","WINE","HANDICRAFTS","SPORTS STADIUMS","GOBBLEDYGOOK","BIOLOGY","FARAWAY PLACES","EATING IN AMERICA","ROCK N' ROLL HEAVEN","HOLLYWOOD HORSES","FURNITURE","ROCKS & MINERALS","SCIENCE TRIVIA","19TH CENTURY","FICTIONAL ANIMALS","MOVIE MONSTERS","NEWSPAPER FILLERS","TOY NAMES","HERBS & SPICES","TV HORSES","FOOD & DRINK","\"NORTH\"","ALL \"THUMB\"S","STARTS WITH \"Z\"","ENGINEERING","Â70S CINEMA","ÂCCÂ","\"ROCK\" & \"ROLL\" SONGS","MISSOURI","PRIMATES","OKLAHOMA","\"UP\" SONGS","DANCE SONGS","MAKEUP","FROGS","COFFEE","TV NUMBERS","CELEBRITY SAYINGS","DIRECTIONS","'50'S TV","AUTO SHOP","SOMETHING \"OLD\"","LOVE","OLYMPIC HISTORY","A.K.A.","\"FOR\" WORDS","NOTABLE ANIMALS","AMERICAN FOLKLORE","STARTS WITH \"G\"","FAMOUS COWS","ORGANIZATIONS","NAMES IN THE NEWS","ANIMAL ADJECTIVES","FAMOUS DUCKS","NOTORIOUS","BRITISH TV","COMPARISONS","PORCUPINES","MONEY SONGS","ARMED FORCES","MULES","\"DANCE\" SONGS","\"K.K.\"","TIES & SCARVES","MEASURE TWICE","ANTS","RACQUET SPORTS","OF \"LOVE\"","BIBLICAL ZOO","THE MIDDLE EAST","FAMOUS SHEPHERDS","THE MILITARY","SPORTSCASTS","VOCABULARY","THE CIVIL WAR","SHOW BIZ SHELLEYS","INCREDIBLE EDIBLES","FRUITS & VEGETABLES","UTILITIES","VITAMINS & MINERALS","REMAKES","SWEETS","DEPARTMENT STORES","THE BRAIN","DOGS IN LITERATURE","'60S SONGS","THE BAHAMAS","\"THE\"","CARS BY THE NUMBER","THOSE DARN OYSTERS","STAMPS & COINS","LYRICS","TV SISTERS","MIDDLE NAMES","NUCLEAR PHYSICS","\"BELL\"S","COLLEGE GRADS","MOVIE TITLE ROLES","FORESTS","RUBBER","\"M\"ENAGERIE","FOLK DANCES","FURRY CREATURES","RESORTS","COUNTIES","QUOTES","FABLES & TALES","WORDS OF THE '80S","END OF THE WAR","HAMLET","GUAM","STUPID GEOGRAPHY","AUTHORS' MAIDEN NAMES","ALPHABETICALLY FIRST","STARTS WITH \"F\"","WATER","TV IN FILM","THE 4TH OF JULY","EVERYDAY SCIENCE","HOUSE PLANTS","THE JUNGLE","READ THE LABEL!","COMMON BONDS","MOVIE DETECTIVES","TRIVIAL WORLD RECORDS","AIRPORTS","NAMESAKES","SINGERS' AUTOBIOGRAPHIES","AMERICAN MUSIC","MARINE BIOLOGY","STERN LOOKING","WARS","N. AMERICAN ANIMALS","POT LUCK","DID YOU NOTICE?","COLLEGES","THE MIDWEST","WORLD RELIGION","MUSICAL INTROS","MEN & WOMEN","\"IN\" & \"OUT\"","START AT THE \"TOP\"","CLOTHING","BRIDGE","BASEBALL LINGO","LITERARY GEMS","\"G\" WHIZ","CRITICALLY SPEAKING","THE MOVIES","N.E.W.S.","MUSICAL MEMORIES","KITCHEN FIRSTS","AMERICANA","TV DETECTIVES","LESOTHO","MAYORS","TV UNCLES","POETRY","CAMELS","SOUTH AFRICA","\"BEAN\" BAG","SHERLOCK HOLMES","ATMOSPHERIC SONGS","GUNS","MEMPHIS","METROPOLITAN OPERA","SPINOFFS","\"OUT\" WORDS","\"JUNGLE\" JIVE","'50S POP","TV THEMES","THE MIDDLE AGES","AUTHORS' MIDDLE NAMES","BROADWAY LYRICS","RUSSIA","'50S TRIVIA","FRANCE","BIOGRAPHIES","THE B&O RAILROAD","THE 50 STATES","IRELAND","MACY'S PARADE","COLONIAL AMERICA","HOLLYWOOD QUOTES","LUNCH COUNTER LINGO","THE KING","ANAGRAMS","THE INSTRUMENT PLAYED","ANCIENT TELEVISION","MOVIE ADJECTIVES","SAN FRANCISCO","3-LETTER FOODS","MISS AMERICA","LOVE & MARRIAGE","FAMOUS CATTLE","LESSER-KNOWN NAMES","DISNEYLAND","WOOD ON THE MAP","FINE CHINA","SHOW MUSIC","LIFE BEGINS AT 40","THE SENSES","SONGS THAT \"DO\"","CHILDREN'S SONGS","SUMMER SONGS","WINES","LANGUAGES","10-HUT!","BIG BANDS","OSCAR-LOSING SONGS","THE YOUNGEST","BEAVERS","BEEF","ANCIENT ROME","BRITISH GHOSTS","BELGIUM","TRANSPORTATION IN FILMS","WOMEN IN HISTORY","MAN IN SPACE","CARTOON BEARS","NAME'S THE SAME","AMY VANDERBILT SAYS","1986","THE JET SET","HIPS","FAMOUS LASTS","STARTS WITH \"P\"","\"RED\"","EASY OPERA","ANTONYMS","SLEEP","1971","EQUIVALENCIES","ONE SONG","BANKING","SPORTS LEGENDS","INDIANS","\"A.C.\"","\"SOME\" SONGS","BEACHES","U.S.A.","IF ANYONE ASKS","BEAUTY SECRETS","STARTS WITH \"K\"","FAMOUS QUOTES","#1 HITS","MOTHER GOOSE","REVOLUTIONARY WAR","MUSIC TRIVIA","SUMMER","PLANTS","STATE FISH","NAME THAT TEAM","CELEBRITY QUOTES","THE HUSBAND MARRIED","NOISEMAKERS","YE GODS","THE MAIN INGREDIENT","PRISONS","COWBOY TALK","GEOGRAPHICAL SONGS","STARRY SONGS","GOING IN STYLE","GET THE \"POINT\"","ADVERTISING MYTHOLOGY","FOREIGN SPORTS","SPACE & AVIATION","RELATIVES IN SONG","THE PACIFIC NORTHWEST","LANGUAGE OF FLOWERS","WORDS","THE FUNNIES","FRANKENSTEIN","RADIO COMEDY","MICE","HONDURAS","GRAY MATTERS","THE VATICAN","TV NOSTALGIA","\"YANKEE\"S","HEROES & VILLAINS","THE LIBRARY","ZEBRAS","ANIMAL RECORDS","BOARD GAMES","HOBBIES","LEAD SINGERS","BUSINESS BIGGIES","NOVEL PLOTS","POP SINGERS","NAUTICAL TRIVIA","\"SQUARE\" DEAL","\"SOUR\"","PBS","ENGLAND","CAR TALK","SINGERS","PLAYTIME","MCDONALD'S","THE UNIVERSE","HEAVY METAL","LIBRARIES","CARTOON QUOTES","CONSTELLATIONS","1982","\"TOP\" THIS","DOLLY PARTON","HOW TO...","WORDS OF THE PAST","HOT DOG!","AMPHIBIANS","MULTIPLE CHOICE","U.S. LANDMARKS","PHYS. ED.","FAMOUS BEARDS","COMIC BOOKS","FOREIGN U.S. CITIES","CRACKER JACK","ANGELS","1-WORD SONGS","\"SOFT\"","TAKE A GUESS","GREETING CARDS","ISRAEL","CELEBRITY SECRETS","PSYCH 101","WHAT'S NEW","WORLD WAR II","FACES","\"ONE, TWO, THREE\"","SEE THE USA","BALD IS BEAUTIFUL","BOGIE","FUNNY MEN","FORMER CAPITALS","YELLOW SONGS","\"BIG\"","THE \"RIGHT\" STUFF","STUDENTS ON TV","SWIMMING & DIVING","BICYCLING","TEEN CLUBS","PALINDROMES","PERFUME","TV ALIENS","OUTDOOR SPORTS","ACTRESSES","\"BUG\"S","MUHAMMAD ALI","FAMOUS PATS","TEEN CUISINE","FAMOUS PARKS","JULY","\"WORLD\"LY SONGS","JAIL","BIBLICAL RESULTS","MOVIE CRITICS","DIRTY WORDS","WORLD OF BEERS","\"MORNING\" SONGS","CELEBRITY TRADEMARKS","DANGEROUS ANIMALS","1951","ANIMAL NOISES","ACCORDING TO SPOCK","SONGS THAT \"COME\" & \"GO\"","COMPLETE THE QUOTE","FAMOUS ROBOTS","B.B.","HEARTTHROBS","THE FOOD BUSINESS","JUNK FOOD","\"BALL\" 1","GEOGRAPHIC PAIRS","BEES","POP MUSIC TRIVIA","PLAYGROUND RHYMES","\"UN\"","FASHION DESIGNERS","FOOTBALL NICKNAMES","1927","SEA CREATURES","BRITISH SUCCESSION","PHONE NUMBERS","FOREIGN PHRASES","THE LETTER G","MARCH","NEW YORK CITY","\"AN\"IMALS","RED SHOES","FITNESS","CLASSIC COUNTRY","FICTIONAL BOYFRIENDS","\"ON\" & \"OFF\" SONGS","VICE-PRESIDENTS","MUSEUMS","1986 FILMS","FAMOUS DOGS","CRIME","IMELDA MARCOS","MORTAL MATTERS","CATS & DOGS","SAINTS","CONTESTS","BOYS IN SONG","SOAP OPERAS","HOLLYWOOD QUEENS","THE SOLAR SYSTEM","ACCESSORIES","GOATS","JAZZ NICKNAMES","NATURAL RESOURCES","AGRICULTURE","AFRICAN ANIMALS","DANCE","WE'RE #2","\"F\" IN FRENCH","ADVERTISING","FEBRUARY","HERALDIC BEASTS","PIGS","BLUNDERS","THE BRITISH ISLES","FAMOUS PAIRS","FEMALE SINGERS","FOLK SONGS","COMPOSERS","(BLANK)","\"WILLIAMS\"","PUNCH LINES","FEMALE FACTS","SPECTATOR SPORTS","STARTS WITH \"I\"","LEAVES","GIANTS","SPECIFICALLY SPEAKING","THE QUEEN'S ENGLISH","ANCIENT RUMORS","FILM GEOGRAPHY","ON THE ROAD","LONDON","ARGENTINA","THE CALENDAR","FOREIGN DINING","ENGLISH LITERATURE","TV COPS","ROMAN EMPIRE","BIBLICAL NAMES","MUSIC FACTS","SIDEWALKS OF NEW YORK","WORLD LEADERS","POINT IT OUT","\"ADVENTURE\" MOVIES","QUESTIONABLE SONGS","NATIONAL AIRLINES","'50S SONGS","WESTERN STARS","ALLITERATIVES","TATTOOS","MUSICAL WOOD","GILLIGAN'S ISLAND","THE BATHROOM","CAESAREAN SECTION","NEW WORDS","MOVIE PAIRS","THOSE DARN ETRUSCANS","DAYS IN SONG","DRAGONS","WOMEN FIRST","HAVE A CIGAR","LITERALLY","OFFICIAL LANGUAGES","SPICY NAMES","CITY NICKNAMES","POST OFFICE","PROVERBS OF DEATH","20TH C. AMERICANS","FICTIONAL CHARACTERS","HEALTH & FITNESS","IN OTHER WORDS...","WOMEN IN SPORTS","IN THE NEWS","THE 20TH CENTURY","MAGAZINE COVERS","DAVID LETTERMAN","STATE FLOWERS","\"LITTLE\"","'80S FASHIONS","THEATER","OLD WEST","HOUSING","THE SOUTH IN SONG","____ THE ____","NORTH DAKOTANS","MILK","ROCK TRIVIA","SESAME STREET","VICTORIAS","DENMARK","MEDICINES","WOOD LIVES!","BIRTHSTONES","AUTHORS","INVERTEBRATES","ICE HOCKEY","\"GLAD\" TIDINGS","1978","SICKNESS & HEALTH","INVENTORS","THE RODEO","REGULAR JOES","FAMOUS ALEXANDERS","WOMEN","BETTE MIDLER","PEN NAMES","POLITICAL PARTIES","THE OLD WEST","CRAZY TALK","\"B\" IN GEOGRAPHY","EARTH SCIENCE","CELEBRITY SPELLING","FAMOUS AMERICANS","NEW YORKERS","HAVE A \"HEART\"","THE CONTINENTS","1966","ENDS WITH \"X\"","FIRST LINES","WEDDING TRIVIA","ANIMAL LOVERS","UNDERWEAR","MYTHS & LEGENDS","COMPARATIVE CUISINE","PHYSICS","BIBLICAL QUOTES","FAMOUS WOLVES","THE 1940S","TV \"LOVE\"","ROMANIA","U.S. GOVERNMENT","SCULPTURE","SAUCES","BEVERLY HILLS","EQIUVALENCIES","CELEBRITIES","THE DESERT","GREAT DAMES","H. G. WELLS","\"G\" WHIZ!","ELECTIONS","2-LETTER WORDS","OIL","\"MAN\"LY MOVIES","LEGS","\"PO\"POURRI","TELEVISION ODDITIES","FROM THE FRENCH","DENTISTRY","\"LEWIS\" & \"CLARK\"","MUSICALS","WOMEN AUTHORS","RIVERS","10-LETTER WORDS","TV ANIMALS","KISSING","BUSINESS '88","THE PLANT KINGDOM","PETER PAN","ROADSIDE AMERICA","APPLES","SMART AS A FOX","\"RICH\"","ROMANTIC LYRICS","GEOGRAPHIC ANAGRAMS","STARTS WITH \"VI\"","TRAVEL TIPS","ACTORS & ACTRESSES","BROWNS","MOUNTAINS","VETERINARY MEDICINE","FLOWERS","MUSICAL METALS","WORDS OF THE '60S","WASHINGTONIANS","STARTS WITH \"J\"","\"SUMMER\"","THE NAVY","STONES","THEME SONGS","SPORTSCASTERS","PRESIDENTIAL NICKNAMES","SHAKESPEAREAN SYNOPSES","TV GUIDE SAYS","NOBEL","WHO CARES?","FOREIGN WORDS","THE HONEYMOONERS","NUTMEGGERS","COMMERCIAL SLOGANS","PIES","SHANGHAI MOVIES","WOMEN IN THE NEWS","FROM THE LATIN","THE CAMERA","MOVIE CLASSICS","MUSICAL RELATIVES","KIDDY LIT CREATURES","POLES","THE STAR-SPANGLED BANNER","INDIANANS","THE OCCULT","CAREERS","TV JOURNALISTS","ACRONYMS","ROYAL ANNES","BIG BAND THEMES","TV INITIALS","I'LL TAKE MANHATTAN","MEDICAL INITIALS","LINDBERGH'S FLIGHT","PASTA","AMERICAN RIVERS","SELF-DEFENSE","FIELD HOCKEY","BALLADS & FOLK SONGS","ENTERTAINING AT HOME","WILL ROGERS","AMERICAN POETRY","STARTS WITH \"CRU\"","THE YEAR THAT WAS","STARTS WITH \"R\"","GOVERNMENT & POLITICS","ARTISTS","STARTS WITH \"V\"","OSCAR-WINNING SONGS","MATHEMATICS","BREAKFAST CEREAL","1987","WILLIE NELSON","WWI PLANES","GONE FISHIN'","THE 1ST TIME SINCE...","NORMAN ROCKWELL","GIVE ME A \"BREAK\"","CRUSTACEANS","SOUTH DAKOTA","WESTERN SONGS","SOCIAL STUDIES","DANCE PARTNERS","ALICE IN WONDERLAND","SPORTING WORDS","PEOPLE & PLACES","NOAH","FLAGS","WINE QUOTES","THE 19TH CENTURY","SHEEP","ODD ROCK WORDS","BORN IN INDIA","BODY LANGUAGE","FLORIDA","ITALIAN ART","HISTORIC NAMES","ACTRESSES' REAL NAMES","COOKING WITH JULIA","SNAKES","HITS OF THE '80S","THE LIBERTY BELL","TURTLES","HAITI","ALPHABET SOUP","WEREWOLVES","PHYSICAL SCIENCE","ADVERTISING NOSTALGIA","BIMINI","SIGNS & SYMBOLS","THE 1880S","COUNTRY CROONERS","TOOLS","SPIRITUAL SONGS","ENDS WITH \"A\"","\"BOO\"!","THE ELEMENTS","HOLY \"COW\"","THE SCENE IS SET","SPIES & SPYING","VIENNA","SOAP","HUMOROUS QUOTES","CHILDREN'S LITERATURE","HOLLYWOOD HISTORY","NUMBER, PLEASE","GAUGES","BACTERIA","COUNTRY SONGS","TRUMAN SPEAKS","SEA SONGS","EUROPEAN MUSEUMS","TV RERUNS","STATISTICS","WORLD LITERATURE","MACHO","STARTS WITH \"W\"","HEADS OF GOVERNMENT","LEATHER","LAST FILMS","WINTER SONGS","\"O\" NO!","MUSIC APPRECIATION","DRUGSTORE","THE SMALLEST","REPTILES","ENDS IN \"TY\"","CHARACTERS IN MUSICALS","8-LETTER SCIENCE","THE PAPAL VISIT","COLORFUL SONGS","LEADERS","TRIVIAL TOURISM","SUPERHEROES","ROCK","SHAKESPEAREAN CHARACTERS","ELVIS","JACKIE GLEASON","AMERICAN HISTORY","JESSICAS","TV CRIMEFIGHTERS","\"BROAD\" MINDED","SOCCER","STATE POSTAL ABBREVIATIONS","GEOLOGY","PLUMBING","RHYMES WITH BANG","ROYAL RUMORS","\"THE\" MOVIES","HOLLYWOOD MARRIAGES","\"LING\" O","COLLEGES & UNIVERSITIES","COLD-BLODDED ANIMALS","LEGAL LINGO","EASY SONGS","FORECASTERS","KNIGHTS","HAJEPODGE","F. SCOTT FITZGERALD","TOYS","WOODY ALLEN FILMS","\"CALIFORNIA\" SONGS","DEFINITIONS","\"Y\" NOT?","THE SOUTH ON FILM","SEALS","ANCIENT EGYPT","EGYPTIAN MYTHOLOGY","MOVIE TEENS","PARIS","SEWING","THE MISSISSIPPI","LAST LINES","HOMOPHONIC PAIRS","ADJECTIVES","SUPERMAN","PUNS","JOAN OF ARC","STAGE NAMES","'87 CINEMA","OLYMPIC MEDALISTS","COSMETICS","5-LETTER \"I\"S","NATIONAL NICKNAMES","MICHIGAN","ACTORS OF THE PAST","HAIR CARE","PARTS OF SPEECH","FERGIE","FRENCH COOKING","JACKS OF ALL TRADES","BASKETBALL","'87 ANNIVERSARIES","MUSICAL JEWELRY","5-LETTER TV SHOWS","6-LETTER PRESIDENTS","7-LETTER CITIES","LONDON MONUMENTS","MEXICO","ENDS WITH \"UNK\"","CELEBRITY RELATIVES","\"UN\" WORDS","THE GIRL SCOUTS","PETES & PETERS","\"M.B.\"","DRUG STORE","RONALD REAGAN","TRAVEL & TOURISM","METALLIC PHRASES","RITA HAYWORTH","\"BACK\" IN SPORTS","SWIMWEAR","TEENS ON TV","CHILD CARE","BIBLICAL GARDEN","PITCHMAN & PRODUCT","TITLES","MEATS","FADS & FASHION","REPUBLICANS","STARTS WITH \"E\"","THIS IS JEOPARDY!","ALLITERATIVE NAMES","AFRICA ON FILM","\"BEAUTIFUL\" MUSIC","DRAMA","\"ANGEL\"IC SONGS","HIT TUNES","THE JETSONS","AMERICAN MOUNTAINS","POLITICAL FIGURES","ANIMAL OFFSPRING","STORYTELLERS","MAPS","20TH C. AMERICA","MAIDEN NAMES","INTERNATIONAL ACTRESSES","WHAT'S \"NEW\"?","PARKS","ALL FALL DOWN","ANIMAL GROUPS","SAINTLY FIRSTS","FINAL RESTING PLACES","ARCHITECTS","GEOGRAPHIC COCKTAILS","'60S TV","NATIONAL SPORTS","ASIAN HISTORY","WARTHOGS","BACK TO THE BEACH","KIDDIE LIT CREATURES","POLO","SPECIAL OSCARS","SPORTS CUPS","KENNY ROGERS","LEMONS","NYC MOVIES","LEGENDARY SINGERS","MOVIES IN OTHER WORDS","AKA","LICENSE PLATES","ENDS IN \"ABLE\"","BEAUTY QUEENS","PRESIDENTIAL LIFESPANS","\"OLD\" & \"NEW\"","HENRYS","GROUPS","CLOTHING IN SONG","CAVES","STARTS WITH \"WH\"","SPANISH CITIES","SPIDERS","MOVIE TAP DANCERS","THE EQUATOR","BILLIARDS","1955","ZEUS","MONEY MATH","OPPOSITES IN SONG","KINGS & QUEENS","MURDER & MAYHEM","CHARLESTON, S.C.","HINTS FROM HELOISE","EUROPE","HORTICULTURE","BATS","BRITISH TRIVIA","TV TAKEOVERS","\"DARK\" SONGS","TENNIS RECORDS","THE REVOLUTIONARY WAR","ACADEMY AWARDS","LIFE SCIENCE","AMERICAN INDIAN NAMES","RECREATION","NEVADA","FOX HUNTING","\"PINK\"","ANTIQUES","\"TIP\" \"TOP\"","SCREEN STARS","\"GOLD\"","GEOGRAPHIC SPELLING","SCANDALS","FARMING","ARTS AND CRAFTS","20TH CENTURY POETRY","COWBOYS & CATTLEMEN","IOWA","\"PAR\" FOR THE COURSE","\"APRIL\" SONGS","THE THIRD WORLD","WYOMING","GUINNESS RECORDS","1988","APOLLO 11","DESSERTS","MR. MOVIES","ANCIENT VIP'S","EUROPE ON FILM","THE ROYAL FAMILY","ARKANSAS","CELEBRITY JEOPARDY!","STAINED GLASS","ROCK 'N' ROLL TRIVIA","\"PO\" POURRI","1887","MISSING LINKS","BASEBALL QUOTES","MISS MANNERS","SPORTS FIGURES","CELEBRITY BOOKS","FLYING ACES","FRENCH PHRASES","BEETHOVEN","SING \"OUT\"","NORTH CAROLINA","PLAYS","THE BIG CATS","SOLITAIRE","SYMPTOMS","\"BAD\"","COUNTRIES","MANIAS","MARTIAL ARTS","TOM SAWYER","OXYMORONS","PRESIDENTIAL RELATIVES","UNCOMMON WORDS","BIRD SONGS","AMY VENDERBILT SAYS","FICTIONAL SISTERS","TV","FILMS!","FAMOUS BROTHERS","WHITE HOUSE WHEELS","DALLAS","MUSICAL \"BELL\"S","THE NETHERLANDS","MEDIUM & MESSAGE","PHILADELPHIA","\"ONLY\" SONGS","MUSICAL WONDERS","\"B\" IN SHAKESPEARE","CREDIT CARDS","19TH CENTURY AMERICA","CINEMATIC ROSES","CRABS","THE U.N.","SPORTS CITIES","CURRENT MONARCHS","HOLLYWOOD LANDMARKS","BLUE JEANS","OPERATING ROOM","HOUSTON","MISSISSIPPI","THE BLUE & THE GRAY","HISTORICAL HORSES","HEADS","CHILDREN'S GAMES","STREET SONGS","\"CORN\"Y WORDS","BRITISH POLITICS","COUNTRY MUSIC TRIVIA","U.S. MILITARY","TOP-SELLING PRODUCTS","THE CONSTITUTION","\"MOORE\" OR \"LES\"","NETWORK BRASS","THE ENVIRONMENT","'50S ADS","CHRISTMAS","U.S. CURRENCY","\"NU\" WORDS","IN THE DICTIONARY","\"PIG\" OUT","DECEMBER 7TH","GEOGRAPHICAL \"SAINT\"S","FILM FACTS","=","SUBURBS","FAMOUS CANADIANS","\"HOUSE\"S","INDIANA","\"GUIDE\"","DRY","SCHOOL DAYS","'88 MOVIES","FAMOUS MORGANS","MUSICAL TEXAS TOWNS","TV WESTERNS","LIGHT","TUNES OF THE '20S","DIAMONDS","THE FIVE & DIME","PENNSYLVANIANS","EARTHQUAKES","PHILOSOPHERS","M*A*S*H","\"PAL\"S","THE 1955 EMMYS","SURVEY SAYS","OOPS!","SEXY SENIORS","\"GIVE\" & \"TAKE\"","THE POST OFFICE","DANCE HISTORY","WIMPY","COLLEGE NICKNAMES","ANIMAL TRIVIA","STEPHEN FOSTER LYRICS","\"LAST\" MOVIES","ACRONYMS & ABBREVIATIONS","POETS","THE HEART","CAMPAIGN '88","\"RIGHT\" SONGS","TV ACTORS & ROLES","CIVIL WAR","COLLEGE SPORTS","ALASKA"];

var allIds = [68,76,94,23,24,56,32,55,1,49,4,84,6,16,67,50,42,19,90,39,64,37,95,98,99,96,33,38,62,25,36,11837,7,105,26,51,17,103,101,81,69,65,14,102,20,18,21,70,80,31,89,13,61,12,35,15,2,63,9,19314,82,30,60,106,79,40,72,46,73,44,22,53,66,29,41,52,97,57,10,34,83,75,78,54,45,87,100,27,5,74,58,77,93,48,88,91,3,71,28,59,104,4897,1239,108,8,107,2865,1238,189,135,187,164,43,128,167,133,198,149,170,132,112,186,172,111,130,202,131,165,153,146,196,1237,195,150,143,119,177,1240,147,193,118,120,159,134,136,127,168,137,201,123,197,124,214,121,182,163,117,184,194,115,174,114,188,1242,199,209,145,122,156,178,180,162,176,154,155,157,175,129,173,125,200,191,151,171,192,160,110,126,210,179,161,190,183,213,204,208,207,144,152,206,113,86,203,212,116,205,166,185,169,1241,138,139,141,142,140,26221,211,220,235,158,292,314,309,261,275,295,236,231,302,317,249,238,287,229,312,274,219,304,221,294,259,319,240,298,223,242,252,269,279,276,226,255,308,313,260,271,267,225,270,320,217,280,244,296,262,250,285,254,253,248,232,245,257,277,297,291,246,264,215,251,282,301,241,268,288,256,283,222,273,227,286,224,305,278,218,216,281,272,284,228,234,299,293,243,258,303,4900,306,307,239,310,311,290,300,315,233,266,318,263,230,247,47,388,316,350,351,336,393,343,391,339,363,415,332,414,362,364,330,428,321,325,356,425,383,353,355,407,370,341,420,358,344,322,347,329,387,340,401,346,349,337,389,333,357,421,361,327,334,365,409,419,328,392,359,360,367,369,348,403,373,366,382,331,390,396,378,352,399,411,398,372,326,385,324,404,381,422,335,418,323,384,402,400,394,338,424,412,408,342,397,406,371,410,413,374,416,417,386,395,375,368,379,377,4898,405,423,2869,354,380,345,471,459,485,444,445,431,482,531,430,478,461,522,501,469,477,466,490,447,494,491,443,451,433,525,436,437,25356,480,481,514,483,472,462,463,484,465,520,453,454,476,499,439,440,504,473,474,475,441,450,446,498,464,506,488,487,458,467,508,442,496,521,519,502,456,500,486,470,435,497,513,529,493,523,495,452,511,429,432,1243,492,510,426,512,449,448,434,515,489,518,517,14446,468,509,507,532,457,526,528,527,479,530,516,455,524,534,460,573,557,571,567,551,552,553,537,558,536,638,554,542,599,1245,559,601,579,626,618,602,570,578,610,627,593,566,572,600,615,583,628,574,555,560,544,545,546,547,543,609,620,539,585,549,550,611,582,568,587,561,594,614,565,588,575,591,562,581,584,595,603,576,577,608,619,607,589,605,586,590,556,538,617,598,624,592,548,612,540,613,580,621,616,2868,604,623,596,533,625,622,535,564,629,631,630,632,636,633,634,635,7452,640,1246,12586,606,696,639,718,655,676,731,659,689,678,642,643,670,700,660,717,644,716,720,721,711,712,734,647,674,699,725,663,646,1244,650,705,714,675,677,727,686,661,652,654,668,641,706,649,685,645,671,662,666,688,664,648,667,669,736,707,682,665,693,701,704,702,703,679,681,673,743,658,697,684,690,691,692,695,651,653,687,713,683,715,719,708,728,729,722,680,724,2867,726,742,672,730,732,723,735,733,656,737,738,739,740,741,710,698,657,694,783,786,804,795,746,753,773,801,826,754,799,752,802,805,792,13467,840,747,780,803,751,825,844,767,798,772,789,815,760,835,847,778,774,4899,769,781,782,768,770,797,771,757,759,811,810,762,822,750,744,806,812,776,843,808,749,785,756,755,787,748,777,791,823,819,796,807,763,809,841,829,818,761,745,817,831,824,821,758,842,830,814,800,816,820,779,765,793,827,828,836,834,833,766,837,838,788,813,794,775,784,846,845,848,839,764,921,849,908,916,877,866,856,909,865,850,901,852,853,917,869,897,911,867,910,894,895,891,947,854,892,880,857,859,864,858,860,887,906,926,883,872,898,873,874,942,861,875,863,884,870,952,955,896,868,855,918,890,950,862,879,933,913,939,936,899,930,888,889,881,915,904,905,893,900,924,907,885,929,938,931,932,925,922,903,851,927,919,920,940,928,953,935,934,937,941,886,876,943,944,945,946,948,2871,951,871,949,912,882,914,878,923,2872,973,1037,956,954,1049,961,1019,1020,974,1057,957,1007,1022,978,985,1048,1038,965,998,963,1000,1013,4896,962,1010,990,1034,976,1042,979,991,1054,1011,1051,1055,966,967,988,1003,986,981,1009,969,1008,983,984,992,960,964,982,1032,1001,1002,1047,958,987,999,996,1045,968,1035,1016,1017,1012,237,1056,1005,975,980,1004,1023,1024,1025,1026,1050,1029,1030,1018,1031,1015,1033,995,1039,1036,7451,1052,1040,1006,1043,1044,997,994,1014,563,972,993,959,989,1053,1027,1046,10539,1028,977,1099,1100,1104,1118,1060,1119,1067,1075,1068,1077,1078,1063,1127,1152,1061,1062,1150,1137,1142,1071,1092,1079,1105,1065,1112,1097,1121,1066,1076,1146,1139,1144,1140,1083,1080,1109,1069,709,1113,1070,1081,1094,1085,1160,1106,1096,1111,1073,1058,1107,1089,1108,1114,1098,1129,1087,1088,1115,1153,1126,1074,1122,1123,1095,1161,1116,1149,1117,1110,1059,1091,1072,1125,1064,1136,1128,1131,1132,1084,1155,1130,1134,1135,1138,1143,1148,1141,1145,1103,1147,1082,1151,1086,1154,2875,1157,1102,1101,1159,1133,1163,1158,1156,13471,1093,1090,1216,1247,1252,1180,1181,1227,1201,1166,1234,1164,1165,1169,1224,1215,1230,1195,1168,1235,1183,1208,1187,1254,1205,1206,1207,1185,1186,1190,1170,1171,1172,1229,1174,1267,1179,1255,1250,1176,1212,1233,1236,1198,1177,1178,1194,1188,1189,1191,1173,1204,1196,1231,1223,1199,1225,1222,1210,503,1202,1218,1269,1193,1203,1209,1162,1214,1167,1221,1213,1200,1253,1226,1263,1197,1251,1232,1175,1228,1256,1264,1219,1258,1211,1248,1249,1257,1182,1259,1261,1217,1262,1268,1266,148,1265,1184,1270,1271,1260,1272,1274,1220,1192,1273,1308,1275,1276,1302,1285,1294,1278,1290,1350,1279,1280,1291,1348,1283,1354,1297,1317,1329,1319,1368,1343,1314,1315,1307,1347,1299,1340,1286,1295,1326,1364,1324,1328,1320,1301,1310,1336,1331,1289,1281,1292,1293,1377,1357,1282,1346,1311,1312,1309,1284,1305,1341,1287,1300,1344,1361,1313,1321,1322,1304,1316,1327,1363,1349,1296,1325,1330,1298,1332,1339,1370,1359,1303,1342,1338,1318,1337,1333,1355,1356,1351,1352,1353,1358,1277,1365,1288,1360,1335,1362,1367,1366,1323,92,1371,1369,1373,1372,1334,1374,1375,1376,1345,1306,1379,1386,1428,1397,1423,1380,1381,1412,1444,1420,1429,1471,1430,1431,1478,1457,1411,1389,1399,1400,1475,1413,1396,1385,1441,1463,1388,1442,1422,1460,1387,1403,1424,1391,1390,1481,1415,1404,1405,1466,1395,1469,1393,1394,1427,1461,1462,1449,1406,1407,1454,1382,1416,1425,1418,1445,1440,1450,1408,1409,1426,1383,1446,1433,1421,438,1419,1410,1401,1434,1435,1436,1378,1437,1392,1443,1476,1402,1452,1448,1455,1456,1451,1453,1464,1474,1447,1470,1467,1465,1438,1459,1472,1473,1398,1432,1458,1477,1414,1479,1480,1482,1439,1468,1384,1523,1524,1525,1483,1573,1541,1486,1560,1588,1503,1583,1520,1570,1578,1518,1500,1501,1521,1504,1557,1488,1485,1489,1532,1509,1490,1505,1506,1536,1553,1528,1516,1517,1531,1494,1546,1492,1491,1519,1495,1507,1508,1510,1496,1497,1499,1511,1548,1549,1550,1529,1530,1561,1527,1522,1562,1514,1512,1513,1582,1563,1564,1538,1487,1540,1534,1569,1545,1552,1544,1535,1577,1547,1542,1565,1576,1586,1556,1493,1526,1502,1554,1551,1543,1566,1559,1568,1498,1539,1572,1484,1571,1574,1575,1567,1579,1581,1580,1533,1558,1584,1585,1555,1587,13996,1638,1666,1606,1515,1600,1656,1675,1590,1591,1603,1665,1632,1599];

var gameBoard = [[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]];
// 0 = main menu,  1 = options, 2 = game, 3 = question , 5 = free play
var scene = 0;
var category = [];
var tempIndex = 0;
var tempCat = 0;
var i;
var dark = false;

function start(val) {
  if (val == 0) {
    transition("title","options");
    document.getElementById("title-logo").style.top = "24px";
    document.getElementById("title-logo").style.fontSize = "24px";
    document.getElementById("header-back").style.left = "20px";
    updateCategories();
    scene = 1;
  } else if (val == 1) {
    transition("options","game",750);
    document.getElementById("title-logo").style.top = "24px";
    document.getElementById("title-logo").style.fontSize = "24px";
    document.getElementById("header-back").style.left = "20px";
    document.getElementById("header-refresh").style.right = "20px";
    document.getElementById("question-a").innerHTML = "";
    refreshCategories();
    scene = 2;
  } else if (val == 2) {
  	//Regular Game
  } else if (val == 3) {
    transition("options","free-play");
    freePlay();
    scene = 5;
  } else if (val == 7) {
    transition("daily-how-to-play", "daily");
    daily();
    scene = 8;
  } else if (val == 8) {
    transition("title", "daily-how-to-play");
    document.getElementById("title-logo").style.top = "24px";
    document.getElementById("title-logo").style.fontSize = "24px";
    document.getElementById("header-back").style.left = "20px";
    scene = 8;
  }
   
}

function back() {
  if (scene == 1) {
    transition("options","title");
  } else if (scene == 2) {
    transition("game","title");
  }	 else if (scene == 3) {
    transition("question","title");
  } else if (scene == 5) {
    transition("free-play","title");
  } else if (scene == 8) {
    transition("daily","title");
  }
  document.getElementById("title-logo").style.top = "25vh";
  document.getElementById("title-logo").style.fontSize = "64px";
  document.getElementById("header-back").style.left = "-24px";
  document.getElementById("header-refresh").style.right = "-24px";
  scene = 0;
}

function changeTheme() {
  if (dark) {
  	document.documentElement.style.setProperty('--c1', '#E26310');
    dark = false;
  } else {
    document.documentElement.style.setProperty('--c1', '#353535');
    dark = true;
  }
}

function transition(to, from, duration) {
  if (duration == null) {
    duration = 300;
  }
  var a = setTimeout(function() {
    document.getElementById(to).style.display = "none";
      document.getElementById(from).style.display = "inline";
      document.getElementById("transition-layer").style.opacity = 0;
    }, duration);
  document.getElementById("transition-layer").style.opacity = 1;
}

function closeQuestion() {
  if (scene == 3) {
    document.getElementById("question").style.display = "none";
    document.getElementById("game").style.display = "inline";
    document.getElementById(tempCat + "-" + (tempIndex+1) * 200).innerHTML = "";
    document.getElementById(tempCat + "-" + (tempIndex+1) * 200).style.background = "none";
    gameBoard[tempCat][tempIndex] = 0;
    document.getElementById("question-a").innerHTML = "";
    scene = 2;
    document.getElementById("header-back").style.display = "inline";
    document.getElementById("header-refresh").style.display = "inline";
    // grey out a finished category
    if (gameBoard[tempCat].every((val, i, arr) => val === 0 )) {
      document.getElementById("game-section-" + tempCat).style.opacity = "0.5";
    }
  } else if (scene == 5) {
    document.getElementById("question").style.display = "none";
    document.getElementById("free-play").style.display = "inline";
    document.getElementById("question-a").innerHTML = "";
  } else if (scene == 8) {
    document.getElementById("question").style.display = "none";
    document.getElementById("daily").style.display = "inline";
    document.getElementById("question-a").innerHTML = "";
    document.getElementById("daily-correct").style.display = "none";
  }
}

for (i=0;i<6;i++) {
  id = Math.floor(Math.random() * 5505);
  getCategories(i, id);
}

function updateCategories() {
  for (i=0;i<6;i++) {
    document.getElementById("cat-" + i).innerHTML = category[i].title.toUpperCase();
    document.getElementById("cat-" + i + "-date").innerHTML = category[i].clues[0].airdate.substring(0,4);
    document.getElementById("game-section-" + i).style.opacity = "1";
    if (category[i].clues.length > 0) {
      document.getElementById(i + "-200").innerHTML = "$200";
      document.getElementById(i + "-200").style.backgroundColor = "var(--c2)";
    }
    if (category[i].clues.length > 1) {
      document.getElementById(i + "-400").innerHTML = "$400";
      document.getElementById(i + "-400").style.backgroundColor = "var(--c2)";
    }
    if (category[i].clues.length > 2) {
      document.getElementById(i + "-600").innerHTML = "$600";
      document.getElementById(i + "-600").style.backgroundColor = "var(--c2)";
    }
    if (category[i].clues.length > 3) {
      document.getElementById(i + "-800").innerHTML = "$800";
      document.getElementById(i + "-800").style.backgroundColor = "var(--c2)";
    }
    if (category[i].clues.length > 4) {
      document.getElementById(i + "-1000").innerHTML = "$1000";
      document.getElementById(i + "-1000").style.backgroundColor = "var(--c2)";
    }
  }
}

function getCategories(i, id) {
fetch('https://jservice.io/api/category?id=' + id)
  .then(response => response.text())
  .then((data) => {
    category.push(JSON.parse(data));
    document.getElementById("cat-" + i).innerHTML = category[i].title.toUpperCase();
  })
}

function refreshCategories() {
  category = [];
  tempIndex = 0;
  tempCat = 0;
  for (i=0;i<6;i++) {
    id = Math.floor(Math.random() * 5505);
    getCategories(i, id);
  }
  setTimeout(function() {
    updateCategories();
  }, 750);
}

function showClue(cat, index) {
  document.getElementById("question").style.display = "inline";
  document.getElementById("game").style.display = "none";
  document.getElementById("question-category").innerHTML = category[cat].title.toUpperCase();
  document.getElementById("question-q").innerHTML = category[cat].clues[index].question;
  tempIndex = index;
  tempCat = cat;
  document.getElementById("header-back").style.display = "none";
  document.getElementById("header-refresh").style.display = "none";
  document.getElementById("question-close").style.display = "inline";
  scene = 3;
}

function showAnswer() {
  if (scene == 3) {
    document.getElementById("question-a").innerHTML = category[tempCat].clues[tempIndex].answer;
  } else if (scene == 5) {
    document.getElementById("question-a").innerHTML = freePlayCategoryData.clues[freePlayIndex].answer;
  } else if (scene == 8) {
    document.getElementById("daily-correct").style.display = "inline";
    if (dailyCat == 0) {
      document.getElementById("question-a").innerHTML = daily0[2][dailyQues];
    } else if (dailyCat == 1) {
      document.getElementById("question-a").innerHTML = daily1[2][dailyQues];
    } else if (dailyCat == 2) {
      document.getElementById("question-a").innerHTML = daily2[2][dailyQues];
    }
  }
}

var players = 3;
function addPlayer(val) {
  players += val;
  if (players < 1) {
    players = 1;
  } else if (players > 5) {
    players = 5;
  }
  document.getElementById("option-number").innerHTML = players;
}

var select = document.getElementById("category-select");
var freePlayOptions = [];
var freePlayIds = [];
var categoryId = 0;

function freePlay() {
fetch('https://jservice.io/api/categories?count=100&offset=1500')
  .then(response => response.text())
  .then((data) => {
    var raw = JSON.parse(data);
    for (i=0;i<100;i++) {
      freePlayOptions.push(raw[i].title.toUpperCase());
      freePlayIds.push(raw[i].id);
    }
    populate();
  })
}

var dailyScore = [['x','x','x','x'],['x','x','x','x'],['x','x','x','x']];
var dailyTurn = 0;
var bonus = false;
var dailyDate;
var score = 0;



var daily0;
var daily1;
var daily2;
var iteration;

function getDailyQuestions(val) {
  if (val == "01/17/2023") {
    iteration = 1;
    daily0 = ["Metals",["The Statue of Liberty is sheathed in more than 31 tons of this metal mined in Norway", "Discovered in Colorado in the 1950s, coffinite is an ore that is more than 60% this radioactive metal","An oxide of this light metal, discovered in 1791, is used extensively as a white pigment","This metal used to make semiconductors was discovered by Clemens Winkler & named for his homeland"],["Copper","Uranium","Titanium","Germanium"]];
    daily1 = ["The Revolutionary War",["The British passed the Intolerable Acts to punish Massachusetts for this event","General Richard Montgomery was killed December 31, 1775 leading a hopeless attack on this Canadian city","Born in Connecticut, Nathan Hale was a graduate of this Ivy League university","In the 1760s painter Charles Willson Peale joined this patriot group, angering Loyalist creditors"],["Boston Tea Party","Quebec","Yale","Sons of Liberty"]];
    daily2 = ["Lakes & Rivers",["Famous for its monster, it forms part of the Caledonian Canal","At 2,485 miles, the Parana is this continent's second-longest river","This largest lake in Africa is also the main reservoir of the Nile River","The pre-Incan Uros people still inhabit floating islands high in the Andes in this lake"],["Loch Ness","South America","Lake Victoria","Lake Titicaca"]];
  } else if (val == "01/18/2023") {
    iteration = 2;
    daily0 = ["Car Talk",["When fixing cars, \"R & R\" means remove & do this to an auto part","This converter reduces the level of harmful pollutants in a car's exhaust","Manual shifters used to come in \"4 on the floor\" & \"3 on\" this arboreal word for the steering column","Inspect the master cylinder, part of the hydraulics sending fluid through the lines for this drum or disc system"],["restore (or replace or repair)","a catalytic converter","tree","the brakes"]];
    daily1 = ["Biology",["Stomata, leaf pores that take in this gas, enlarge when its level in the air drops below normal","This 3-letter suffix denotes a carbohydrate, especially a sugar","There are 3 main types of these in the body--smooth, striated & cardiac","This part of the small intestine is named for the fact that it's about as long as the width of 12 fingers"],["carbon dioxide","-ose","muscles","duodenum"]];
    daily2 = ["5-Letter Words",["To surpass, or a Microsoft spreadsheet program","Honey is an animal product & can be excluded from a strict this type of diet","A musical composition with a repeated theme using multiple voices, or a disturbed state of altered consciousness","The Carabao is a popular variety of this tropical fruit"],["excel","vegan","fugue","mango"]];
  } else if (val == "01/19/2023") {
    iteration = 3;
    daily0 = ["Communication",["56' wide & 29' high, a digital billboard called the Broadway Spectacular is in the heart of this New York City area","With a brain larger than man's, their language is a system of beeps, whistles, & clicks","The 2-way field radio developed by Don Hings for bush pilots in 1937 soon got this snappier name","France's Robert Coulondre, who had this job, presented a futile demarche, a diplomatic note, in Berlin Sept. 1, 1939"],["Times Square","dolphins","walkie-talkies","ambassador to Germany"]];
    daily1 = ["Mississippi",["On Jan. 9, 1861, Mississippi became the 2nd state to do this","In 1898 in Biloxi, Edward Barq began bottling & selling this beverage","He modeled his fictional Yoknapatawpha County on the area around his hometown of Oxford","Over 55% of the land in Mississippi is covered by these"],["secede from the Union","root beer","(William) Faulkner","forests"]];
    daily2 = ["Vocabulary",["If you're piscivorous, you eat this, which can \"net\" you some health benefits","Latin gets its name from \"Latium\", a region of this country","Sometimes it's a pickled flower bud used as a garnish, & sometimes it's a prank or theft","From the Latin for \"earth\", it's another word for patio"],["fish","Italy","a caper","terrace"]];
  } else if (val == "01/20/2023") {
    iteration = 4;
    daily0 = ["Weather",["On a weather map, 3 horizontal & parallel lines indicate this weather condition","From the Middle English for \"fall of dew\", it's a light rain in which the water droplets are less than .5 mm in diameter","Non-fluid aneroid barometers use a partial one of these instead of mercury to measure air pressure","The highest known barometer reading in the U.S., 31.85, was recorded in this state during a 1989 cold wave"],["fog","drizzle","vacuum","Alaska"]];
    daily1 = ["American History",["He died in 1804 the day after his duel with Aaron Burr","Without the knowledge of Congress, James Madison took possession of West Florida from this country","In the 1850s this state was \"Bleeding\" as pro- & anti-slavery forces met up in a preview of the Civil War","The \"separate but equal\" doctrine in the case of Plessy v. this judge upheld racial segregation for almost 60 years"],["Alexander Hamilton","Spain","Kansas","Ferguson"]];
    daily2 = ["Old Testament",["\"And the Lord spake unto the fish and it vomited out\" him \"upon the dry land\"","In the 1st month of their 2nd year in the desert, Moses & the people celebrated this holiday","Leviticus 13 is a symptom guide for this skin disease you hear a lot about in the Bible","Isaiah & Jeremiah are considered major ones, Obadiah & Zechariah, minor"],["Jonah","Passover","leprosy","prophets"]];
  } else if (val == "01/21/2023") {
    iteration = 5;
    daily0 = ["Spiders",["Each of a spider's these contains 7 segments, so that's 56 segments per spider","The spider family Uloboridae lacks these glands, so if you want a pet spider, maybe get one of them","Many garden spiders are among those classed as these \"weavers\" of round webs","1 of the world's most dangerous spiders is this country's Sydney funnel web"],["legs","venom","orb weavers","Australia"]];
    daily1 = ["Europe",["This country that has many satellites built a monument to its 1st satellite","Rossini never visited this Spanish city where he set an 1816 opera","This is the largest & southernmost of the Baltic republics","Bonny Ben Nevis, highest peak in the United Kingdom is in this country"],["Russia","Seville","Lithuania","Scotland"]];
    daily2 = ["Golf",["Bird word for 2 under par on a hole","The \"pitching\" this type of club is used for short, lofted shots","The closely mowed ring of grass around a putting green is called an apron or this out-there name","Exhibiting Bernoulli's Principle, these indentations on a golf ball cause it to lift & stabilize it in flight"],["an eagle","wedge","the fringe","a dimple"]];
  } else if (val == "01/22/2023") {
    iteration = 6;
    daily0 = ["Rock 'N Roll",["In \"American Pie\", Don McLean drove this to the levee","The concert theatrics of this band included Pete Townshend smashing his guitar to bits","Peter & Gordon's hit, \"World Without Love\", was written by this Beatle pair","In 1985, Tears for Fears said \"everybody wants to\" do this"],["Chevy","The Who","Lennon & McCartney","rule the world"]];
    daily1 = ["Pop Music",["Ariana Grande sings, \"When all is said & done, you will believe\" this, a 2018 song that mixes spirituality & female power","A song by Zedd, Maren Morris & Grey asks, \"Oh baby, why don't you just meet me in\" this title place","In 2015 Zayn Malik officially quit this band","\"Somebody Told Me\" that The Killers were formed in this city in 2002"],["\"God Is A Woman\"","the middle","One Direction","Las Vegas"]];
    daily2 = ["Opera",["This opera ends with the title madam committing hara-kiri","Don Jose is bewitched by this title gypsy girl","Mozart opera in which the count tries to thwart & postpone his valet's wedding","Peter Cornelius' opera \"The Barber of Baghdad\" was based on a tale in this collection"],["Madame Butterfly","Carmen","The Marriage of Figaro","Arabian Nights"]];
  } else if (val == "01/23/2023") {
    iteration = 7;
    daily0 = ["Cats",["An old name for Thailand is in the name of this breed that sometimes has crossed eyes","Shorthaired cats were derived from the caffre cat, which was domesticated by this ancient civilization","In the 1960s officials of the Ankara, Turkey zoo saved this pure breed from extinction","Kittens have 26 of these, adult cats 30"],["a Siamese","Egypt","the Turkish Angora","teeth"]];
    daily1 = ["Food Facts",["This word was once used for the meat of any hunted animal; now it refers to deer meat","A genoise is a light sponge cake whose name is derived from this city","Mostly made from the whites, egg substitutes don't contain fat or this artery-clogging lipid","Cannellini is a white kidney bean, cannelloni is a type of this"],["venison","Genoa","cholesterol","pasta"]];
    daily2 = ["Medicine",["The A1C test measures average blood sugar over the past 3 months; at 5.7% you're pre-this, at 6.5 you're this","In this \"effect\" people are given inert substances & seem to improve","Named for an American surgeon, McBurney's incision is a cut in the lower right abdomen used when removing this","Often found in areas with large deer populations, this bacterial inflammatory disease was first identified in 1975"],["diabetic","placebo","the appendix","Lyme disease"]];
  } else if (val == "01/24/2023") {
    iteration = 8;
    daily0 = ["Flags",["Fiji's flag depicts many of its tropical treasures, including sugar cane, bananas & this type of palm","The diamond shape on its flag references the fact that it was the only diamond-producing U.S. state","The fortress on the flag of this British overseas territory symbolizes its strategic importance on the Mediterranean","The blue & white in Somalia's flag were influenced by the flag of this body that has played a role in Somali history"],["a coconut tree","Arkansas","Gibraltar","the United Nations"]];
    daily1 = ["Children's Literature",["Sketches written for Punch became his first novel, \"Lovers in London\"; Winnie-the-Pooh came 21 years later","\"One Sunday morning the warm sun came up and--pop!--out of the egg came\" this title larva","A young rabbit gets ready for bed in this classic by Margaret Wise Brown","Thing One & Thing Two are characters in this 1957 Seuss classic"],["(A.A.) Milne","the Very Hungry Caterpillar","Goodnight Moon","The Cat in the Hat"]];
    daily2 = ["Animal Adjectives",["Vulpine, like the bat-eared or the crab-eating","Ostracean, like the Olympia or the pearl","Anserine, like the snow or the nene","Columbine, like the rock or the mourning"],["the fox","an oyster","a goose","a dove"]];
  } else if (val == "01/25/2023") {
    iteration = 9;
    daily0 = ["Mathematics",["The exact value of this, the ratio of a circle's circumference to its diameter, can't be written down","This type of \"strip\", a continuous flat loop with 1 twist, has only 1 surface","In Roman numerals, the largest number represented by a single letter with no markings","A set with no elements is described as this"],["pi","a Möbius strip","1,000 (the letter M)","Null / empty"]];
    daily1 = ["Science",["Every second, fusion reactions in the Sun convert about 600 million tons of this element into helium","Newly created nihonium is classified as a \"trans-\" this element","During a total solar eclipse, you can glimpse this \"colorful\" layer of the Sun just above the photosphere","First predicted in 1930, this particle with no charge goes through miles of matter without reacting with a proton or neutron"],["hydrogen","transuranium","the chromosphere","neutrinos"]];
    daily2 = ["History",["An international force seized Beijing on August 14, 1900, crushing this rebellion","Name of the king who after beating Rome at Asculum but taking heavy casualties, said one more such win would undo him","In 1950 & then again in 1951, this capital city fell to invading forces who were evicted each time by U.N. troops","The USA's worst depression before the Civil War began with what's usually called this event \"of 1837\""],["the Boxer Rebellion","Pyrrhus","Seoul","the Panic"]];
  } else if (val == "01/26/2023") {
    iteration = 10;
    daily0 = ["Geography",["Lahore, this country's second-largest city, is the capital of the Punjab province","This Italian region that includes Pisa & Florence gets its name from the Etruscan people","If you're on Nevis & have business at Government House, you need to go to this nearby island","Afrikaner Gert Alberts was the leader of a famous crossing of this desert in the 1870s"],["Pakistan","Tuscany","St. Kitts","the Kalahari Desert"]];
    daily1 = ["Languages",["Standard Chinese is based primarily on this form of Chinese spoken by the educated in Beijing","This language is spoken by about 11 million in Europe & about 200 million in South America","L.L. Zamenhof grew up in an area of Poland where 4 languages were spoken, leading to ethnic animosity, so he created this","The language of this small Balkan country has 2 main dialects: Gheg & Tosk"],["Mandarin","Portugese","Esperanto","Albania"]];
    daily2 = ["Constellations",["The brightest star in Bootes is this color giant & is 100 times more luminous than the sun","With this constellation winding around it, Ursa Minor must hope it isn't fire-breathing","The Pup is the companion to this star in Canis Major","This constellation's second-brightest star, Shaula, is also known as \"the Stinger\""],["red","Draco","Sirius (the Dog Star)","Scorpio"]];
  } else if (val == "01/27/2023") {
    iteration = 11;
    daily0 = ["Dragons",["In this novel, Bilbo Baggins, Gandalf & 13 dwarves reclaim Lonely Mountain & its riches from the dragon Smaug","In Babylonian myth, the dragon Tiamat's upper half becomes Heaven; the lower half, this","This Scandinavian prince rid the Danes of the monster Grendel; 50 years later he was killed by a dragon","Last name of King Arthur's father Uther, derives from the Welsh, meaning \"head\" or \"chief\""],["The Hobbit","the earth","Beowulf","Pendragon"]];
    daily1 = ["Farming",["Driving 20-ton vehicles on farmland can mean that the next year you'll get \"stuck in\" one of these, defined as a wheel track 3\" deep","In July 2019 dozens of farmers of these beans went to congress, demanding a deal be made to resume trading with China","Heinz sauces--er, sources--ketchup tomatoes from this state's vast & fertile Central Valley","Applied to farmland, it means left without sowing for a period in order to restore its fertility"],["a rut","soybeans","California","fallow"]];
    daily2 = ["Guinness Records",["Takabisha, the steepest one of these, has a free-falling angle of 121 degrees; your move, Space Mountain","Talk about a special day! Romanian model Ema Dumitrescu's wedding dress had a 1.85-mile-long one of these","A 1759 document records Arthur Guinness signing a 9,000-year lease on a brewery at St. James' Gate in this city","In 2004, Tia, a mastiff, gave birth to the largest litter of these ever--24"],["a rollercoaster","a train","Dublin","puppies"]];
  } else if (val == "01/28/2023") {
    iteration = 12;
    daily0 = ["Words",["This name for a work of art that you may carve in art class comes from the Latin for \"to carve\"","The name of these small towers often seen on castles comes from Old French for \"small towers\"","This word for a white wine & soda drink first appeared in Webster's in 1961","A harsh expression substituted for a more neutral one is a dysphemism & this is the opposite"],["sculpture","turrets","spritzer","euphemism"]];
    daily1 = ["Chemistry",["The lipids, which include fats & oils, are organic compounds that don't appreciably interact with this","Relative atomic mass is another name for this","Acids & bases are among these current conductors; using a solid instead of a liquid one reduces the risk of fire in batteries","This brown pigment of hair, skin & eyes is a polymer"],["water","atomic weight","electrolytes","melanin"]];
    daily2 = ["Games",["Each player is dealt 26 cards in this game; if both players turn up a card of the same rank, it's this, the name of the game","In the game of Hearts, this card is known as \"The Black Lady\"","Join in & tell us that this is the lowest-rated suit in contract bridge","In U.S. croquet, a ball that goes through all the wickets has this travelling name, especially if it's the red one"],["War","the queen of spades","clubs","a rover"]];
  } else if (val == "01/29/2023") {
    iteration = 13;
    daily0 = ["Fitness",["Sprinting & powerlifting are examples of this type of exercise that means \"without oxygen\"","Referring to exercise that raises your heart rate and gets your blood flowing, \"cardio\" is short for this","To improve balance, try this ancient exercise with a Chinese name that means \"supreme ultimate fist\"","It's the \"electrical\" term for the amount of weight or pressure involved in an exercise"],["anaerobic","cardiovascular","tai chi","resistance"]];
    daily1 = ["Ancient Rome",["The last emperor of Rome, who was overthrown in 476, shared his name with this legendary founder of the city","Carved on stone or metal, the acta diurna was an early newspaper posted this often in a public area","Roman roads were built with concrete made from pozzolana, ash from these; the roads by Pompeii must've been good","Latin for \"father of the family\", he was the oldest living male of the family & had total control of his household"],["Romulus","daily","volcanoes","pater familias"]];
    daily2 = ["Plants",["In 2006 the city of L.A. Iimited its planting of this tall tree because it's disease-prone, non-native & gives little shade","Archaeologists have found that varieties of this grain, like Emmer & Einkorn, were grown in the 7th millennium B.C.","Fungi not only lack roots, stems & leaves, but also this food-making matter","This tree's name comes from the Hindi word for \"trader\" because people displayed their wares in its shade"],["the palm","wheat","chlorophyll","the banyan tree"]];
  } else {
    iteration = 0;
    daily0 = ["cat0",["q0","q1","q2","q4"],["a0","a1","a2","a4"]];
    daily1 = ["cat1",["q0","q1","q2","q4"],["a0","a1","a2","a4"]];
    daily2 = ["cat2",["q0","q1","q2","q4"],["a0","a1","a2","a4"]];
  }
}

function daily() {
  document.getElementById("myScore").style.visibility = "none";
  dailyScore = [['x','x','x','x'],['x','x','x','x'],['x','x','x','x']];
  dailyTurn = 0;
  bonus = false;
  score = 0;
  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0');
  var yyyy = today.getFullYear();

  today = mm + '/' + dd + '/' + yyyy;
  dailyDate = today;
  document.getElementById("daily-date").innerHTML = today;
  getDailyQuestions(today);
  document.getElementById("daily-category0").innerHTML = daily0[0];
  document.getElementById("daily-category1").innerHTML = daily1[0];
  document.getElementById("daily-category2").innerHTML = daily2[0];
}

var dailyCat = 0;
var dailyQues = 0;

function dailyQ(cat,ques) {
  if (dailyScore[cat][ques] == 'x' && dailyTurn < 10) {
    showClueDaily(cat,ques);
    dailyCat = cat;
    dailyQues = ques;  
  }
}

function dailyCorrect(val) {
  document.getElementById("daily" + dailyCat + "-q" + dailyQues).style.borderColor = "var(--c1)";
  document.getElementById("daily" + dailyCat + "-q" + dailyQues).style.cursor = "auto";
  if (val == 0) {
    document.getElementById("daily" + dailyCat + "-q" + dailyQues).style.backgroundColor = "white";
    dailyScore[dailyCat][dailyQues] = 0;
  } else {
    document.getElementById("daily" + dailyCat + "-q" + dailyQues).style.backgroundColor = "var(--c1)";
    dailyScore[dailyCat][dailyQues] = 1;
    score++;
  }
  dailyTurn++;
  closeQuestion();
  if (dailyTurn == 9) {
    document.getElementById("daily0-q3").style.display = "inline-block";
    document.getElementById("daily1-q3").style.display = "inline-block";
    document.getElementById("daily2-q3").style.display = "inline-block";
  } else if (dailyTurn == 10) {
    document.getElementById("daily-share").style.display = "inline-block";
    var i;
    for (i=0;i<3;i++) {
      if (dailyScore[i][3] == 'x') {
        document.getElementById("daily" + i + "-q3").style.backgroundColor = "white";
        document.getElementById("daily" + i + "-q3").style.border = "white";
        document.getElementById("daily" + i + "-q3").style.cursor = "auto";
      }
    }
  }
}

function showClueDaily(cat, index) {
  document.getElementById("question").style.display = "inline";
  document.getElementById("daily").style.display = "none";
  if (cat == 0) {
    document.getElementById("question-category").innerHTML = daily0[0];
    document.getElementById("question-q").innerHTML = daily0[1][index];
  } else if (cat == 1) {
    document.getElementById("question-category").innerHTML = daily1[0];
    document.getElementById("question-q").innerHTML = daily1[1][index];
  } else if (cat == 2) {
    document.getElementById("question-category").innerHTML = daily2[0];
    document.getElementById("question-q").innerHTML = daily2[1][index];
  }
  tempIndex = index;
  tempCat = cat;
  document.getElementById("header-back").style.display = "none";
  document.getElementById("header-refresh").style.display = "none";
  document.getElementById("question-close").style.display = "none";
}

function share() {
  var result = "";
  var i;
  var j;
  for (i=0;i<3;i++) {
    for (j=0;j<4;j++) {
      if (dailyScore[i][j] == 0) {
        result += "⬜";
      } else if (dailyScore[i][j] == 1) {
        result += "🟧";
      }
    }
    result += "\n";
  }
  result += "\nCalpardy Daily #" + iteration + "\n" + dailyDate + "\n" + score*10 + "%" + "\n\ncalvinchristensen96.github.io/calpardy";
  document.getElementById("myScore").value = result;
  var copyText = document.getElementById("myScore");
  copyText.select();
  copyText.setSelectionRange(0, 99999);
  navigator.clipboard
  .writeText(copyText.value)
  .then(() => {
    alert("Your score has been copied to your clipboard.\n\nThank you for playing!");
  })
  .catch(() => {
    alert("Unable to copy to clipboard. Please copy message manually to share.\n\nThank you for playing!");
  });
  document.getElementById("myScore").style.visibility = "visible";
}

function populate() {
  //document.getElementById("free-play-board").innerHTML = freePlayOptions + "<br><br>" + freePlayIds;
  for(var i = 0; i < allCats.length; i++) {
    var opt = allCats[i];
    var optId = allIds[i];
    var el = document.createElement("option");
    el.textContent = opt;
    el.value = optId;
    select.appendChild(el);
  }
  sortSelect(select); 
}

function sortSelect(selElem) {
    var tmpAry = new Array();
    for (var i=0;i<selElem.options.length;i++) {
        tmpAry[i] = new Array();
        tmpAry[i][0] = selElem.options[i].text;
        tmpAry[i][1] = selElem.options[i].value;
    }
    tmpAry.sort();
    while (selElem.options.length > 0) {
        selElem.options[0] = null;
    }
    for (var i=0;i<tmpAry.length;i++) {
        var op = new Option(tmpAry[i][0], tmpAry[i][1]);
        selElem.options[i] = op;
    }
    return;
}

function freePlayChange() {
  document.getElementById("free-play-questions").style.display = "block";
  freePlayGetClues(document.getElementById("category-select").value);
}

function freePlayGetClues(val) {
  fetch('https://jservice.io/api/category?id=' + val)
  .then(response => response.text())
  .then((data) => {
    var raw = JSON.parse(data);
    freePlayCreateTable(raw);
  })
}

var freePlayCategoryData;
var freePlayIndex;
function freePlayCreateTable(raw) {
  freePlayCategoryData = raw;
  var curDate = raw.clues[0].airdate;
  var table = false;
  var result = getDate(raw.clues[0].airdate) + '<br>';
  for (i=0;i<raw.clues.length;i++) {
    if (raw.clues[i].airdate != curDate) {
      result += '</table>';
      table = false;
      result += '<br>' + getDate(raw.clues[i].airdate) + '<br>';
      curDate = raw.clues[i].airdate;
    } else {
      if (!table) {
	    result += '<table class="free-play-table">';
        table = true;
      }
      if (raw.clues[i].value == null) {
        raw.clues[i].value = 'DD';
      }
      result += '<td id="value' + i + '"onClick="showClueFreePlay(' + i + ')" style="background-color: var(--c2);">' + raw.clues[i].value + '</td>';
    }
  }
  document.getElementById("free-play-questions").innerHTML = result;
}

function showClueFreePlay(index) {
  document.getElementById("value" + index).style.backgroundColor = "white";
  freePlayIndex = index;
  document.getElementById("question").style.display = "inline";
  document.getElementById("free-play").style.display = "none";
  document.getElementById("question-category").innerHTML = freePlayCategoryData.title.toUpperCase();
  document.getElementById("question-q").innerHTML = freePlayCategoryData.clues[index].question;
  document.getElementById("header-back").style.display = "none";
  document.getElementById("header-refresh").style.display = "none";
}

// Takes a string in YYYY-MM-DD and returns in Month Day, Year.
function getDate(str) {
  var month = str.substring(5,7);
  if (month == '01') {
    month = 'January';
  } else if (month == '02') {
    month = 'February';
  } else if (month == '03') {
    month = 'March';
  } else if (month == '04') {
    month = 'April';
  } else if (month == '05') {
    month = 'May';
  } else if (month == '06') {
    month = 'June';
  } else if (month == '07') {
    month = 'July';
  } else if (month == '08') {
    month = 'August';
  } else if (month == '09') {
    month = 'September';
  } else if (month == '10') {
    month = 'October';
  } else if (month == '11') {
    month = 'November';
  } else if (month == '12') {
    month = 'December';
  }
  var day = str.substring(8,10);
  var year = str.substring(0,4);
  var result = month + ' ' + day + ', ' + year;
  return result;
}
